### ISSUE TITLE
Add datastore and UI support for neo4j

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1010]
With MetaModel 4.5.0 we will be able to easily add neo4j support.

**Comment by ClaudiaPHI** [comment]
TODO: 

- [ ] Make a Datastore class for it
- [ ] Add conf.xml support (read+write)
- [ ] Add desktop dialog

**Comment by ClaudiaPHI** [comment]
I have created a branch for this issue: feature/1010-neo4j-support.

**Comment by ClaudiaPHI** [comment]
This is a prototype. There are some bugs regarding Neo4j to solve in Metamodel before we can merge this into master.
