### ISSUE TITLE
Remote components interfaces -- immutability

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1022]
This is an issue about refactoring mutable interfaces in remote components part. The following is Kasper's citation: 

Regarding the discussion on immutability, OptionsDialog and RemoteServerData (which somehow got lost inbetween the commits - grrrr github): For me this is not a blocker, so we can leave it as is, but I would like to explain it because immutability is close to my heart and it's anyways something I think we will run into later:

My suggestion was to make the objects truly immutable. So no setters, and all fields final. The reason for this is that these objects are shared between many subprocesses and changing it is actually pretty dangerous - it might happen in the middle of a subprocess running in the background, yielding errors and cornercase scenarios at unpredictable places. And with a batch processing tool like DC this is very likely because you may have jobs running at the same time someone is changing the configuration.

Immutability is a common answer to this problem: Make sure that the data cannot mutate. If you need different data, create a copy with the changes incorporated in it. So from that point of view, if the user opens the OptionsDialog, then when saving the dialog I would create a completely new RemoteDescriptorProvider with completely new RemoteServerData objects. That way any lingering processes will not be impacted, but new job executions etc. will use the new descriptors.

**Comment by kaspersorensen** [comment]
No longer applies to CE
