### ISSUE TITLE
Scrollbar thumbs can get quite hard to notice in results

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1040]
Just had a job with a huge amount of values in value distribution, and I thought we had a bug because I didn't see the scrollbar thumb, as it is tiny with that many rows. We should probably make it a liiiittle larger.

![image](https://cloud.githubusercontent.com/assets/1282832/12198554/5dae9a5a-b611-11e5-954f-76d1025a7f94.png)

**Comment by ClaudiaPHI** [comment]
I have been researching and I did not find a way to increase the size of the knob/thumb scroll.

**Comment by LosD** [comment]
How about: ```UIManager.put( "ScrollBar.minimumThumbSize", new Dimension( wanted_width, wanted_height ) )```?

http://stackoverflow.com/questions/22762715/change-jscrollbar-thumb-size

**Comment by LosD** [comment]
(I think we have a equivalent DC-centric thing)

**Comment by ClaudiaPHI** [comment]
I couldn't. The scrollbar is attached to a component obtained from a Renderer. I tried to the solution suggested and it doesn't work so far.

**Comment by kaspersorensen** [comment]
Try to set it with the other UI Properties in class LookAndFeelManager

**Comment by ClaudiaPHI** [comment]
I created a value distribution on id for 500 000 records. The panel is very big. 
![image](https://cloud.githubusercontent.com/assets/6339923/12299444/0befedc2-ba17-11e5-9290-8ef6bbf6aae6.png)

**Comment by ClaudiaPHI** [comment]
Value distribution on the first name for a file with 500 000 records. The minimum height of the scroll is 30. 

![image](https://cloud.githubusercontent.com/assets/6339923/12299537/7e196b4e-ba17-11e5-8c88-86c387ed355b.png)
