### ISSUE TITLE
Can't preview transformation when another/unrelated component is not configured

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1042]
I noticed today that if I try to preview a transformation, then even a "dangling" (completely unconfigured - only placed on the canvas) component can make my preview fail.

![image](https://cloud.githubusercontent.com/assets/291450/12245553/99e9d616-b8a9-11e5-8cbe-fac3a47f01c0.png)

I suggest to do two fixes:

 * First improve the error message since in this case we could tell which component's configuration is causing the issue.
 * Secondly make the preview function ignore completely irrelevant components to the extent feasible.

**Comment by ClaudiaPHI** [comment]
The error comes from the unconfigured component.
