### ISSUE TITLE
DC monitor - cannot edit all the alerts

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1051]
![image](https://cloud.githubusercontent.com/assets/6339923/12289430/c938c2c8-b9db-11e5-9a74-1bceb2c4de0d.png)

The UI doesn't give access to all the alerts of a job

![image](https://cloud.githubusercontent.com/assets/6339923/12289456/e8fc9c38-b9db-11e5-884f-59373373a8e8.png)

**Comment by kaspersorensen** [comment]
I guess this is just a (hopefully simple) CSS tweak that we need to do.

**Comment by ClaudiaPHI** [comment]
New version: 
![image](https://cloud.githubusercontent.com/assets/6339923/12327507/440f77a2-bad7-11e5-9743-a0cfe2840d41.png)
