### ISSUE TITLE
Union produces null values when input columns have name clashes

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1056]
With a Union configuration like this (using orderdb):

![image](https://cloud.githubusercontent.com/assets/291450/12327654/07aed694-bad8-11e5-9490-8af4a7c180e8.png)

Then the country and state values (which clash in column name) are only materialized for one of the two unioned tables:

![image](https://cloud.githubusercontent.com/assets/291450/12327688/3088356a-bad8-11e5-94a3-8b91df03d17c.png)

I suppose this somehow has to do with the identification of columns by name.

**Comment by LosD** [comment]
This was only happening in the master branch, right?

**Comment by kaspersorensen** [comment]
That might actually be the case yes. I just tried it at my home computer which runs DC 4.5.2 - and could not reproduce it there.

**Comment by LosD** [comment]
Seems to be the same in DC 4.5.3:
![image](https://cloud.githubusercontent.com/assets/1282832/12392162/333dd2ca-bded-11e5-9554-d404b21b62a0.png)

**Comment by LosD** [comment]
Changing to #1064 for now, as it is more critical bug (affects all users of union, not this special case).
