### ISSUE TITLE
Dc monitor- error while creating datastore 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1061]
I have chosen to create a CSV  datastore, but I uploaded an excel file.  
The error I got it is not explanatory enough. 
![image](https://cloud.githubusercontent.com/assets/6339923/12353319/56c1107e-bb8e-11e5-9135-82df05dec12b.png)

Should it be allowed to upload an excel file in the first place ? 
I guess we use the same upload form for all the datastores type.

**Comment by arjansh** [comment]
I don't get the error anymore. The datastore is created successfully. However when I try to query it I get nonsensical results (for .xlsx) or no results (for .xls). I guess it should not be allowed to upload an excel file here.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
