### ISSUE TITLE
Add a default remote descriptor provider

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1071]
Recent changes has been made to make sure that conf.xml does not need to specify any descriptor provider but instead can rely on defaults. This is being done to ensure that upgrading conf.xml is easier, and that copying it from e.g. desktop to monitor (typically to move just the datastores and reference data) can also be done without having to worry about the effect on more "environment" aspects such the storage provider, descriptor provider etc.

Right now the default descriptor provider is a classpath scanner that scans ```org.datacleaner```, ```com.hi``` and ```com.neopost``` (see ```DesktopConfigurationReaderInterceptor``` (desktop) and ```application-context.xml``` (monitor)).

**Comment by jakubneubauer** [comment]
For this time of being different approach was chosen - because user credentials are needed for remote components on DataCloud, a "welcome" dialog was introduced and remote descriptor provider is saved to conf.xml together with credentials.

**Comment by jakubneubauer** [comment]
... and by default, no remote connection is configured.
