### ISSUE TITLE
Avoid RepositoryZipController.uploadRepository(...) from deleting old repository if input file is empty

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1077]
I was testing the restore functionality of ```RepositoryZipController.uploadRepository(...)``` the other day and found that it is quite dangerously just replacing the contents of the repo - even if the new is completely blank.

I would say that we should _at least_:

 * Check that the input file is valid - that it at least has basic repo characteristics like being a zip file, containing a conf.xml file etc.
 * Place the old repo in tmp files for possible cancellation.

**Comment by LosD** [comment]
In addition, to make this a bit more safe, create a zip of the original repo, and tell the user where to find it.
