### ISSUE TITLE
Javadoc generation fails when using java 8

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1078]
Java 8 is more strict when it comes to Javadoc (see http://openjdk.java.net/jeps/172). As a result you cannot generate javadoc (e.g. through the `mvn javadoc:javadoc` command) when using java 8.

**Comment by arjansh** [comment]
Note that you can work around this by suppressing the doclint checks (by adding `<additionalparam>-Xdoclint:none</additionalparam>` to the appropriate poms.

**Comment by kaspersorensen** [comment]
As long as we still support Java 7 (but hey, that's not needed anymore for v5.0) then we shouldn't add this ```additionalparam``` because it breaks the build on JDK7. I would actually prefer if we could fix the javadoc issues there are (at least the errors which cause JDK8 build failure), but it might be a too big task.

**Comment by LosD** [comment]
I would LOOOOOOOVE to fix those issues instead of doing the Xdoclint trick.

**Comment by kaspersorensen** [comment]
I tried to reproduce but couldn't. ```mvn javadoc:javadoc``` and ```mvn site``` works fine here.

I also had a recollection of fixing it, and found a PR from a few months ago which did that: #895

@arjansh did you try this on the master branch?

**Comment by arjansh** [comment]
@kaspersorensen I tried this on the master branch. For me `mvn javadoc:javadoc` fails with errors like these:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:javadoc (default-cli) on project DataCleaner-api: An error has occurred in Ja
vaDocs report generation:
[ERROR] Exit code: 1 - C:\git\DataCleaner\api\src\main\java\org\datacleaner\api\AnalyzerResultFuture.java:64: warning: no description for @param
[ERROR] * @param listener
[ERROR] ^
[ERROR] C:\git\DataCleaner\api\src\main\java\org\datacleaner\api\AnalyzerResultFuture.java:71: warning: no description for @param
[ERROR] * @param listener
[ERROR] ^
[ERROR] C:\git\DataCleaner\api\src\main\java\org\datacleaner\api\AnalyzerResultFuture.java:43: warning: no description for @param
[ERROR] * @param <R>
[ERROR] ^
```

When I execute `mvn site` it goes into an endless loop.

**Comment by LosD** [comment]
That's weird, I'm pretty sure those are supposed to be warnings, not errors.
