### ISSUE TITLE
Remote components - Limitation of size of batch request.

### ISSUE THREAD

**Issue by khouzvicka** [datacleaner/DataCleaner#1122]
Maximum size of batch request will be 50 lines.

**Comment by kaspersorensen** [comment]
Can you provide more info about the reason for this limitation? Not that I think it's a problem, but without any reason it just seems arbitrary :)

**Comment by khouzvicka** [comment]
We would like to prevent huge negative credit balance. When user has very low credit and he will do very big batch request, his credit will be very negative. This restriction don't resolve negative balance completely, but some restriction is necessary. 50 is good compromise.

**Comment by kaspersorensen** [comment]
But the lockout mechanism is asynchronuous I believe, so anyways time-bound rather than request bound. Or am I wrong (sounds like a discussion to have internally instead of on this issue though).

**Comment by khouzvicka** [comment]
You are right. The lockout mechanism is asynchronous.
I will do new solution. Batch size will be set by set method. And we will set it in datacloud app context.
Behavior will be same, but we will able to change this limit in datacloud.

**Comment by jakubneubauer** [comment]
fixed by #1123
