### ISSUE TITLE
datacleaner.sh has been saved as a DOS/Windows text files.

### ISSUE THREAD

**Issue by chubbard16** [datacleaner/DataCleaner#1125]
The 4.5.4 release installs datacleaner.sh as a DOS/Windows files on a linux system. The command dos2unix or similar is required to converted the file before it can be used.

**Comment by LosD** [comment]
Aw, man. I though we'd found and fixed all of those. This probably also affects Macs

**Comment by kaspersorensen** [comment]
When we fix it again, I suggest to invest a bit of time into enforcing that it stays this way somehow. Not sure exactly how, but I can imagine there are maven build plugins or such that can verify it during the build.
