### ISSUE TITLE
Satori Address cleansing component should fail on remote error

### ISSUE THREAD

**Issue by chubbard16** [datacleaner/DataCleaner#1133]
The current implementation of the Satori Address cleansing component continues processing records after receiving an error[s] from the IAC server. Errors are passed back to Data Cleaner in the "Address correction code" and "Address correction message". It looks like Data Cleaner treats this as a data value and not as a error status. An example of such an error is shown below

_"Client error","IAC service error: Client received SOAP Fault from server: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs. Please see the server log to find more detail regarding exact cause of the failure."_

When errors similar to this happen, it would be good to have the option to fail fast or maybe set a threshold to the number of acceptable errors before failing.

**Comment by kaspersorensen** [comment]
No longer applicable to community edition.
