### ISSUE TITLE
HdfsUrlChooser does not time out when trying to load from an unresponsive machine

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1150]
Whenever a user tries to browse an unresponsive Hadoop cluster/namenode, the timeout will take forever (I'm not sure if that is literal or not, at least much, much longer than reasonable).

What makes it worse, is that there's no way to cancel the wait, so the DC Window is essentially useless while waiting.

Try to make a timeout on the connection, so that the user doesn't have to wait forever. This probably shouldn't apply to the actual execution of jobs, as we don't want to kill those unless the server is really, truly dead. But maybe make sure that the cancel button works also when dealing with an unresponsive server.

**Comment by arjansh** [comment]
I looked into this issue, but where I know I could produce it a couple of days ago, I can no longer reproduce it now. I do get a stacktrace now when I try to use/select an unresponsive Hadoop cluster/namenode. This stacktrace contains an IllegalArgumentException wrapping an UnknownHostException.

**Comment by arjansh** [comment]
The issue can be reproduced by trying to connect to a hdfs node of which the hostname is known, but which is not running.

The `HdftUrlChooser.HdfsDirectoryModel#updateFileList()` method invoke the `org.apache.hadoop.fs.FileSystem#listStatus(Path)` method which by default tries for a quarter of an hour (15 minutes) to get a connection, after which it throws an IOException if it isn't able to get a connection within that time frame.

**Comment by LosD** [comment]
Nice find! :) Can you see an easy way to change the timeout?

**Comment by arjansh** [comment]
I'm looking into that right now. By default it has a timeout of 20 seconds and retries 45 times.

**Comment by LosD** [comment]
Wow, that's... Agressive

**Comment by arjansh** [comment]
Then we catch the IOException and continue as though everything is fine and invoke the same method a bit later, which adds another 15 minutes to the wait.

**Comment by LosD** [comment]
Whoooops

**Comment by arjansh** [comment]
You can add a property named `ipc.client.connect.max.retries.on.timeouts` to the core-site.xml and set its value to 0 to change the number of retries from 45 to 0, which will make the HdfsUrlChooser timeout within a minute. This is however most probably not advisable for production environments.

**Comment by LosD** [comment]
No, I'm thinking it is something we should do on the actual connection, if possible. I think it requires getting the configuration from the HadoopResource (if any), and then adding it to that programmatically afterwards.
