### ISSUE TITLE
SynonymCatalog + Dictionary filenames in conf.xml gets double scheme

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1160]
There seems to be an issue with the resource path (```<filename>```) of the file-based dictionaries and synonym catalogs in conf.xml when being edited by the desktop dialogs for this.

After saving a synonym catalog, then restarting datacleaner and then editing it again, I get a filename like this:
```
<filename>file://file:/datastores/job_title_synonyms.txt</filename>
```

Note: This particular example is a relative path (datastores/job_title_synonyms.txt) within DataCleanerHome. I have not tried it with an absolute path.

**Comment by LosD** [comment]
I don't really mind, as long as there is some level of guarantee that the matching isn't different depending on the path. If there isn't, I really think that it is a step backwards.

**Comment by kaspersorensen** [comment]
Been looking further into this issue ... It seems that it's a bit misunderstood in it's original description. What I see is:

If I have a properly formatted "resource" path in filename, such as this:
```
<filename>file://datastores/job_title_synonyms.txt</filename>
```
Then the UI of DC shows it without one of the initial slashes, like this:

![image](https://cloud.githubusercontent.com/assets/291450/13107381/ab096e94-d56d-11e5-9213-a43d401570ea.png)

I imagine that this is causing the problem. So I'll start from there to see howcome it is being loaded from the XML with only one slash.
