### ISSUE TITLE
ElasticSearch connection type not saved to conf.xml

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1169]
I experience that if I create an ElasticSearch datastore in the desktop UI then the conf.xml entry that is created does not tell which connection type it has. And then when reloading the conf.xml file upon DC restart then it falls back to TRANSPORT client mode. If the original connection type was either REST or NODE then it means the datastore is no longer working.

**Comment by ClaudiaPHI** [comment]
Can you @LosD review this issue ?

**Comment by LosD** [comment]
Oh, I fixed that recently.

**Comment by LosD** [comment]
Fixed here #1332
