### ISSUE TITLE
remote component icon overlay looks ugly

### ISSUE THREAD

**Issue by jakubneubauer** [datacleaner/DataCleaner#1173]
Especially for components with blue or green icons.

**Comment by jakubneubauer** [comment]
What about this:
![remote-overlay-proposal](https://cloud.githubusercontent.com/assets/1188613/13153775/ffde0a84-d675-11e5-9f9f-733656882428.png)

**Comment by jakubneubauer** [comment]
@kaspersorensen can you, please, comment the proposed solution? icon overlay was put outside of the main icon, in the same way as an "error" indicator is implemented. The error indicator has place in lower left corner. So I used upper right 1) to not collide, 2) because it intuitively corresponds to the "wi-fi" association.

**Comment by jakubneubauer** [comment]
So with error it looks this:
![remote-with-error](https://cloud.githubusercontent.com/assets/1188613/13154014/217c3c14-d677-11e5-9b61-953777629115.png)

**Comment by kaspersorensen** [comment]
I think that's a good improvement!
I might still also consider adding a bit of semi-transparent white as background/outline for the green symbol. But the proposal there certainly helps a lot! How does it look in the component tree? I was thinking maybe we should change the color of the text in the tree to indicate that it's remote.

**Comment by jakubneubauer** [comment]
I was considering to not use the overlay in the tree (it is so small there, it cannot be recognized by user anyway). And yes, I think that text color could work. Will not be straightforward, but once the user get it, it works.

**Comment by jakubneubauer** [comment]
This is my best try for small icon overlays. Please, vote.

![overlay-small-screenshot](https://cloud.githubusercontent.com/assets/1188613/13172445/576dc456-d6f8-11e5-87b3-156768a30770.png)

**Comment by jakubneubauer** [comment]
made PR #1175 with the latest proposals. If some change arises from this discussion, we can modify that branch.

**Comment by kaspersorensen** [comment]
Hmm the green color used here does not really fit that well IMO.

I'm thinking maybe we shouldn't even have an overlay in the tree. But instead just make the text color different (maybe the same purple as the DataCloud logo). Or maybe add some other text-effect like italic or underline.

**Comment by kaspersorensen** [comment]
Fixed some time ago by correcting the colors and style of the remote components' icons.
