### ISSUE TITLE
Swagger UI: REST client does not work -- bad URL

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1189]
Swagger UI webapp provides REST client where a user can try the service. It does not work though, because of a wrong URL that is provided by the SwaggerJSONController.

The reason for this behaviour at DataCloud is the nginx configuration / load-balancing / redirecting. For this case a special HTTP header "X-Original-Url" is provided. This should be used in SwaggerJSONController as a priority:

```
if request.headerExists("X-Original-Url"):
  url = request.getHeader("X-Original-Url")
else:
  url = header.getHost() // older way
```

**Comment by jakubneubauer** [comment]
Fixed by #1194
