### ISSUE TITLE
Preview still has issues

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1192]
Even though we did a lot of preview-fixing, we're still having issues at a customer. The job looks like
Table->Equals filter->Concatenator->Whitespace trimmer

Previewing the concatenator gives fine results, but previewing the whitespace trimmer gives `<null>` for all inputs and outputs.

**Comment by LosD** [comment]
Filters also still seems to sometimes miss. In this case table->regex parser (1)->null check filter--NOT_NULL-->regex parser (2)--match-->remove substring 

Remove substring review will contain the NULLs from the filter.

**Comment by LosD** [comment]
(Again, sorry about wayyyy to little details, but in the middle of preparing stuff for tomorrow's customer workshop)

**Comment by ClaudiaPHI** [comment]
I was able to reproduce the first case (with whitespace trimmer) with this job: 
``` 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job xmlns="http://eobjects.org/analyzerbeans/job/1.0">
    <job-metadata>
        <job-description>Created with DataCleaner Enterprise edition 5.0-SNAPSHOT</job-description>
        <author>claudiap</author>
        <updated-date>2016-03-04+01:00</updated-date>
        <metadata-properties>
            <property name="CoordinatesX.PUBLIC.ORDERS">56</property>
            <property name="CoordinatesX.PUBLIC.CUSTOMERS">50</property>
            <property name="CoordinatesY.PUBLIC.CUSTOMERS">83</property>
            <property name="CoordinatesY.PUBLIC.PAYMENTS">33</property>
            <property name="CoordinatesX.PUBLIC.PAYMENTS">30</property>
            <property name="CoordinatesY.PUBLIC.ORDERS">56</property>
        </metadata-properties>
    </job-metadata>
    <source>
        <data-context ref="orderdb"/>
        <columns>
            <column id="col_customernumber" path="PAYMENTS.CUSTOMERNUMBER" type="INTEGER"/>
            <column id="col_checknumber" path="PAYMENTS.CHECKNUMBER" type="VARCHAR"/>
            <column id="col_paymentdate" path="PAYMENTS.PAYMENTDATE" type="TIMESTAMP"/>
            <column id="col_amount" path="PAYMENTS.AMOUNT" type="NUMERIC"/>
        </columns>
    </source>
    <transformation>
        <transformer>
            <descriptor ref="Convert to number"/>
            <metadata-properties>
                <property name="CoordinatesY">166</property>
                <property name="CoordinatesX">86</property>
            </metadata-properties>
            <properties>
                <property name="Decimal separator" value="&amp;#44;"/>
                <property name="Minus sign" value="-"/>
                <property name="Null replacement" value="&lt;null&gt;"/>
                <property name="Thousand separator" value="."/>
            </properties>
            <input ref="col_amount"/>
            <output id="col_amountasnumber" name="AMOUNT (as number)"/>
        </transformer>
        <transformer requires="outcome_0">
            <descriptor ref="Concatenator"/>
            <metadata-properties>
                <property name="CoordinatesY">231</property>
                <property name="CoordinatesX">388</property>
            </metadata-properties>
            <properties>
                <property name="Separator" value=" &amp;#44; "/>
            </properties>
            <input ref="col_customernumber"/>
            <input ref="col_checknumber"/>
            <input ref="col_paymentdate"/>
            <input ref="col_amount"/>
            <input ref="col_amountasnumber"/>
            <output id="col_concatofcustomernumberchecknumberpaymentdateamountamountasnumber" name="Concat of CUSTOMERNUMBER,CHECKNUMBER,PAYMENTDATE,AMOUNT,AMOUNT (as number)..."/>
        </transformer>
        <transformer requires="_any_">
            <descriptor ref="Whitespace trimmer"/>
            <metadata-properties>
                <property name="CoordinatesY">350</property>
                <property name="CoordinatesX">651</property>
            </metadata-properties>
            <properties>
                <property name="Trim left" value="true"/>
                <property name="Trim right" value="true"/>
                <property name="Trim multiple to single space" value="false"/>
            </properties>
            <input ref="col_concatofcustomernumberchecknumberpaymentdateamountamountasnumber"/>
            <output id="col_concatofcustomernumberchecknumberpaymentdateamountamountasnumbertrimmed" name="Concat of CUSTOMERNUMBER,CHECKNUMBER,PAYMENTDATE,AMOUNT,AMOUNT (as number)... (trimmed)"/>
        </transformer>
        <filter>
            <descriptor ref="Equals"/>
            <metadata-properties>
                <property name="CoordinatesY">261</property>
                <property name="CoordinatesX">201</property>
            </metadata-properties>
            <properties>
                <property name="Compare values" value="[ 5307.98 ]"/>
            </properties>
            <input ref="col_amountasnumber" name="Input column"/>
            <outcome id="outcome_0" category="EQUALS"/>
        </filter>
    </transformation>
    <analysis>
        <analyzer>
            <descriptor ref="Create CSV file"/>
            <metadata-properties>
                <property name="CoordinatesX">680</property>
                <property name="CoordinatesY">40</property>
            </metadata-properties>
            <properties>
                <property name="File" value="file://datastores/orderdb-Whitespace trimmer.csv"/>
                <property name="Separator char" value="&amp;#44;"/>
                <property name="Quote char" value="&amp;quot;"/>
                <property name="Escape char" value="\"/>
                <property name="Include header" value="true"/>
                <property name="Encoding" value="UTF-8"/>
                <property name="Fields" value="[Concat of CUSTOMERNUMBER&amp;#44;CHECKNUMBER&amp;#44;PAYMENTDATE&amp;#44;AMOUNT&amp;#44;AMOUNT (as number)...,Concat of CUSTOMERNUMBER&amp;#44;CHECKNUMBER&amp;#44;PAYMENTDATE&amp;#44;AMOUNT&amp;#44;AMOUNT (as number)... (trimmed)]"/>
                <property name="Overwrite file if exists" value="true"/>
            </properties>
            <input ref="col_concatofcustomernumberchecknumberpaymentdateamountamountasnumber" name="Columns"/>
            <input ref="col_concatofcustomernumberchecknumberpaymentdateamountamountasnumbertrimmed" name="Columns"/>
        </analyzer>
    </analysis>
</job>
```

**Comment by ClaudiaPHI** [comment]
I believe that I reproduced the second case as well. 
´´´
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job xmlns="http://eobjects.org/analyzerbeans/job/1.0">
    <job-metadata>
        <job-description>Created with DataCleaner Enterprise edition 5.0-SNAPSHOT</job-description>
        <author>claudiap</author>
        <updated-date>2016-03-04+01:00</updated-date>
        <metadata-properties>
            <property name="CoordinatesX.PUBLIC.ORDERS">56</property>
            <property name="CoordinatesX.PUBLIC.CUSTOMERS">42</property>
            <property name="CoordinatesY.PUBLIC.CUSTOMERS">33</property>
            <property name="CoordinatesY.PUBLIC.PAYMENTS">33</property>
            <property name="CoordinatesX.PUBLIC.PAYMENTS">30</property>
            <property name="CoordinatesY.PUBLIC.ORDERS">56</property>
        </metadata-properties>
    </job-metadata>
    <source>
        <data-context ref="orderdb"/>
        <columns>
            <column id="col_customernumber" path="CUSTOMERS.CUSTOMERNUMBER" type="INTEGER"/>
            <column id="col_customername" path="CUSTOMERS.CUSTOMERNAME" type="VARCHAR"/>
            <column id="col_contactlastname" path="CUSTOMERS.CONTACTLASTNAME" type="VARCHAR"/>
            <column id="col_contactfirstname" path="CUSTOMERS.CONTACTFIRSTNAME" type="VARCHAR"/>
            <column id="col_phone" path="CUSTOMERS.PHONE" type="VARCHAR"/>
            <column id="col_addressline1" path="CUSTOMERS.ADDRESSLINE1" type="VARCHAR"/>
            <column id="col_addressline2" path="CUSTOMERS.ADDRESSLINE2" type="VARCHAR"/>
            <column id="col_city" path="CUSTOMERS.CITY" type="VARCHAR"/>
            <column id="col_state" path="CUSTOMERS.STATE" type="VARCHAR"/>
            <column id="col_postalcode" path="CUSTOMERS.POSTALCODE" type="VARCHAR"/>
            <column id="col_country" path="CUSTOMERS.COUNTRY" type="VARCHAR"/>
            <column id="col_salesrepemployeenumber" path="CUSTOMERS.SALESREPEMPLOYEENUMBER" type="INTEGER"/>
            <column id="col_creditlimit" path="CUSTOMERS.CREDITLIMIT" type="NUMERIC"/>
            <column id="col_jobtitle" path="CUSTOMERS.JOBTITLE" type="VARCHAR"/>
        </columns>
    </source>
    <transformation>
        <transformer>
            <descriptor ref="Regex parser"/>
            <metadata-properties>
                <property name="CoordinatesY">253</property>
                <property name="CoordinatesX">40</property>
            </metadata-properties>
            <properties>
                <property name="Mode" value="FIND_ALL"/>
                <property name="Pattern" value="^&amp;#91;C&amp;#93;&amp;#91;A-Za-z&amp;#93;*"/>
            </properties>
            <input ref="col_contactlastname"/>
            <output id="col_contactlastnamecnames" name="CONTACTLASTNAME ( 'C' names)"/>
        </transformer>
        <transformer requires="outcome_0">
            <descriptor ref="Regex parser"/>
            <metadata-properties>
                <property name="CoordinatesY">603</property>
                <property name="CoordinatesX">719</property>
            </metadata-properties>
            <properties>
                <property name="Mode" value="FULL_MATCH"/>
                <property name="Pattern" value="&amp;#91;C&amp;#93;&amp;#91;a&amp;#93;&amp;#91;a-z&amp;#93;*"/>
            </properties>
            <input ref="col_contactlastnamecnames"/>
            <output id="col_contactlastnamecanames" name="CONTACTLASTNAME ( 'Ca' names) "/>
        </transformer>
        <transformer requires="outcome_0">
            <descriptor ref="Remove substring"/>
            <metadata-properties>
                <property name="CoordinatesY">297</property>
                <property name="CoordinatesX">483</property>
            </metadata-properties>
            <properties>
                <property name="Case sensitive" value="false"/>
                <property name="Match whole words only" value="false"/>
            </properties>
            <input ref="col_fullname" name="Base text column"/>
            <input ref="col_contactlastnamecanames" name="Substring columns"/>
            <output id="col_fullnamecanamesremoved" name="Fullname  ('Ca' names removed)"/>
        </transformer>
        <transformer>
            <descriptor ref="Concatenator"/>
            <metadata-properties>
                <property name="CoordinatesY">102</property>
                <property name="CoordinatesX">264</property>
            </metadata-properties>
            <properties>
                <property name="Separator" value=" "/>
            </properties>
            <input ref="col_contactlastname"/>
            <input ref="col_contactfirstname"/>
            <output id="col_fullname" name="Fullname"/>
        </transformer>
        <filter>
            <descriptor ref="Null check"/>
            <metadata-properties>
                <property name="CoordinatesY">231</property>
                <property name="CoordinatesX">274</property>
            </metadata-properties>
            <properties>
                <property name="Consider empty string as null" value="false"/>
                <property name="Evaluation mode" value="ANY_FIELD"/>
            </properties>
            <input ref="col_contactlastnamecnames"/>
            <outcome id="outcome_0" category="NOT_NULL"/>
        </filter>
    </transformation>
    <analysis>
        <analyzer>
            <descriptor ref="Create CSV file"/>
            <metadata-properties>
                <property name="CoordinatesY">86</property>
                <property name="CoordinatesX">1007</property>
            </metadata-properties>
            <properties>
                <property name="File" value="file://C:/Users/claudiap/Desktop/removeString.csv"/>
                <property name="Separator char" value="&amp;#44;"/>
                <property name="Quote char" value="&amp;quot;"/>
                <property name="Escape char" value="\"/>
                <property name="Include header" value="true"/>
                <property name="Encoding" value="UTF-8"/>
                <property name="Fields" value="[CONTACTLASTNAME (matched part) (matched part) (substring removed),CONTACTLASTNAME (matched part),CONTACTLASTNAME (matched part) (matched part),Fullname]"/>
                <property name="Overwrite file if exists" value="true"/>
            </properties>
            <input ref="col_fullnamecanamesremoved" name="Columns"/>
            <input ref="col_contactlastnamecnames" name="Columns"/>
            <input ref="col_contactlastnamecanames" name="Columns"/>
            <input ref="col_fullname" name="Columns"/>
        </analyzer>
    </analysis>
</job>

```

**Comment by LosD** [comment]
For a while, I suspected an error in the actual running code, but the main issue seems to be that we're sometimes misunderstanding the actual requirements flow, and also did when implementing the preview: If a component gets it own requirement, it will ignore requirements coming from another component through input columns. So when the preview add max rows to the second component (as it does to all components, the original requirement will be lost.

I'm not actually sure what to do about it. We may be able to reduce the impact by only applying the max rows to components that aren't already affected by it through its input columns, but I'm not sure that it will catch all cases.
