### ISSUE TITLE
Make it possible to trigger a monitor job remotely

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1198]
If someone has an export running, it would be really nice to advice DC that it has completed, and a DC job can run.

A nice way to do make that possible could be some kind of HTTP request.

**Comment by kaspersorensen** [comment]
Already exists, see "trigger job" web service in the docs :-)

**Comment by LosD** [comment]
Oh, nice :)

I just saw that there was no "external trigger" option in the scheduling, and made a silly assumption :)
