### ISSUE TITLE
Spark submit to Hadoop merges analysis results for Value Distribution Analyzer

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1242]
When you create a job with a Value Distribution Analyzer with more than one column selected in the input columns, when running the job normally the analysis results shows result tabs for each selected column. If you however use spark submit to run the job on a Hadoop cluster, it seems to merge the analyzed values of all columns into on set an renders the one result tab for all values in all input columns (when you download the result file from the hdfs and open it in DataCleaner). Something similar happens when you use the Pattern Finder Analyzer.

**Comment by LosD** [comment]
I see the issue with the value distribution, but not the pattern finder.
