### ISSUE TITLE
Cannot run OrderDB Customers and Employees union example job

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1274]
When I open the `OrderDB Customers and Employees union.analysis.xml` example job, I cannot click the execute button, because the job configuration seems to be invalid the job analyzer builder windows shows this message:
`Job error status: Create staging table validation failed: Field names must be unique. Field name 'contactfirstname' occurs multiple times.`

**Comment by ClaudiaPHI** [comment]
This has been fixed.
