### ISSUE TITLE
DataCleaner community edition contains commercial edtion only example jobs 

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1275]
A number of the example jobs can't be opened from the DataCleaner community edition release, because they need the commercial edition to work:
- dedup_customers_detection.analysis.xml
- dedup_customers_training.analysis.xml
- OrderDB Customers dedup Training.analysis.xml
- OrderDB Customers Duplicate detection.analysis.xml
- OrderDB Name and Phone Cleansing.analysis.xml

It would seem logical if these are not shipped with the community edition release, but only with the commercial releases.

**Comment by ClaudiaPHI** [comment]
Yes. It is not a bug.

**Comment by ClaudiaPHI** [comment]
This is what I have been telling you this morning that you need to test it with enterprise edition.

**Comment by ClaudiaPHI** [comment]
Sorry. I didn't read all the comment.

**Comment by ClaudiaPHI** [comment]
Fixed by https://github.com/datacleaner/DataCleaner/pull/1598/files
