### ISSUE TITLE
Repaint remote indicator to black color

### ISSUE THREAD

**Issue by khouzvicka** [datacleaner/DataCleaner#1277]
As a user I like to use the remote components. It's simple and easy I am not even aware that they are working remote. Even the icons on these components are not immediately refllecting that. Theyu do it in a subtle way by providing a wifi element on the icon. That element is in green and hardly visible on green and blue colored icons. If we make it black its more visible that you are using remote components ...

**Comment by ClaudiaPHI** [comment]
Closing this because https://github.com/datacleaner/DataCleaner/pull/1278 was dropped.
