### ISSUE TITLE
exposing remote component as remote component doesn't work

### ISSUE THREAD

**Issue by jakubneubauer** [datacleaner/DataCleaner#1290]
If DC monitor connects to DataCloud to get remote components and then the DC monitor itself is used as a server for remote components, the remote components exposed as remote components don't work.
Specifically, the enumerations types that are only in DataCloud classpath (not in monitor classpath) don't work.

**Comment by LosD** [comment]
There's something cool about remote-remote components, but is there a use case where this is an actual issue?

**Comment by jakubneubauer** [comment]
Yeah, we want to support scenario for MDM/Datahub - they run their own monitor, which should use DataCloud components. So basically we want to support running jobs on monitor that is connected to another monitor for remote components.
To be honest, I'm not sure if they will need to expose those remote components from their own monitor, or if they just want to run the jobs on it... It is my presumption based on my understanding of what is Datahub connector. This is definitely a knowledge I need to get from the MDM team.

**Comment by LosD** [comment]
If it's a quick fix, it would be nice to make it possible, just in case someone can make something nice from it (maybe for proxying/load balancing components?), but if it is a lot of work we may want to make sure it will be used :)

**Comment by jakubneubauer** [comment]
Yes, the fix is not big, see the PR #1292.
