### ISSUE TITLE
Large complex XML(2,5 GB) file can't be used as source

### ISSUE THREAD

**Issue by markansink** [datacleaner/DataCleaner#1293]
When loading a large xml file as a source in DC I get an GC overhead exception. I think because DC is trying to parse the file in order to get the columns. See attachment.

[datacleaner.txt](https://github.com/datacleaner/DataCleaner/files/212773/datacleaner.txt)

I can't use the XSD to avoid DC to scan and parse the file.

**Comment by kaspersorensen** [comment]
You do have the option to specify the column paths yourself, which makes our connector ample for large XML files also.

See https://datacleaner.org/resources/docs/5.0/html/ch11s02.html#configuration_file_datastore_xml

**Comment by markansink** [comment]
Thanks. But it would be a nice improvement if you can load the XSD to define the table structure. It saves a lot of manual labour.

**Comment by kaspersorensen** [comment]
I understand, but XML documents are not tabular by nature - they can have arbitrary (hierarical) structures. And the same thus goes for XSDs - they can define any xml structure so we cannot expect to automatically derive a table model from it. So we do need a human being to do the mapping towards a table structure. Of course it would be very nice to have more help in doing this for sure. Some kind of UI where you can see a preview of your logical tables - and maybe also some way to easily pick table/column paths from a XML snippet. But that's another story then which I will encourage you to write up :)
