### ISSUE TITLE
Datacloud Icon in notification panel and status panel

### ISSUE THREAD

**Issue by khouzvicka** [datacleaner/DataCleaner#1296]
We can make the connection visible, for instance by adding a DataCloud icon in the status bar of DataCleaner (where it now reads "Community edition'). That icon can reflect the connection status (green if all's fine, yellow if credits are out, grey if not configured). A mouseover could display username and credit balance, and we can provide a link directly to the dc.org credit balance or history page (including the login - we know the password  ). This will make the integration even more tight.

**Comment by ClaudiaPHI** [comment]
Closing because the issue was solved in https://github.com/datacleaner/DataCleaner/pull/1300
