### ISSUE TITLE
DataCloud status panel - minor bugs

### ISSUE THREAD

**Issue by khouzvicka** [datacleaner/DataCleaner#1314]
1) When user is connected and will change credentials to other correct credentials. Status panel will be with old credentials.
2) Better messages about problems with connection to DataCloud.

**Comment by LosD** [comment]
@khouzvicka did the merged commit completely fix this? Then you need to write "Fixes" in front of the bug number, so GitHub can autoclose the bug.

**Comment by LosD** [comment]
(Of course that's too late for this issue, just close it manually if nothing is missing)
