### ISSUE TITLE
Simple dictionary dialog looks garbled

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1316]
When you open the simple dictionary dialog, it doesn't look good (see screenshot). If you resize it, making it higher, once you cross a threshold it reorganizes itself to look as expected again.

**Comment by arjansh** [comment]
![2016-04-21 12_26_21-simple dictionary _ datacleaner](https://cloud.githubusercontent.com/assets/16542747/14705932/4fb4aeb0-07bc-11e6-976e-47d921108507.png)

**Comment by jhorcicka** [comment]
Screenshot from Linux: 
![dictionary-linux](https://cloud.githubusercontent.com/assets/13213915/14706813/31b38314-07c1-11e6-84b2-79a4f5bb0eb4.png)
