### ISSUE TITLE
EBCDIC fixed width files support

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1330]
Support for input data fixed-width files in EBCDIC encoding is required. In GUI dialog for fixed-width datastore this new encoding (and perhaps other options) should be added. Main changes will be in MetaModel itself.

**Comment by LosD** [comment]
I don't think we'll need a new encoding (It's in there, called IBM-some-number). However, there may be a need for the autodetection to understand no EOL characters.
