### ISSUE TITLE
DataCloud welcome dialog does not show

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1344]
When starting DataCleaner without a DataCloud connection, the dialog should show automatically, but since 5.0.3 it doesn't. It also doesn't show when clicking the DataCloud info panel's "Sign in to DataCloud" button.

**Comment by LosD** [comment]
Okay, is not as bad as I first thought. The reason it doesn't show for is It is just because we once clicked "Don't show again" in the welcome screen.

The button in the DataCloud info panel should show it unconditionally, though.

**Comment by ClaudiaPHI** [comment]
It's not relevant anymore, therefore I am closing the issue

**Comment by LosD** [comment]
It is very much relevant still.

**Comment by LosD** [comment]
### Prerequisites
Do not be logged into DataCloud, Datacleaner not started (or Welcome dialog already set to "Do not show again".

### Steps to reproduce
1. Start DataCleaner
1. Click "Do not show again" on welcome dialog.
1. Close dialog.
1. Click DataCloud icon in status bar.
1. Click "Sign in to DataCloud" in sidebar.

### Actual result
Nothing happens

### Expected result
Welcome dialog or setting dialog on DataCloud tab shows up so credentials can be added.

**Comment by kaspersorensen** [comment]
No longer relevant since DataCloud is not in community edition.
