### ISSUE TITLE
Enable configuration of reference data in the monitor

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1352]
The monitor has no way of working with the reference data, making it necessary to upload a new configuration file. This is a pretty error-prone process, both because of the ease and tough consequences of corrupting the file, but also simply because there's a good chance the user will be juggling several configuration files, making it easy to use the wrong one.

**Comment by LosD** [comment]
Not necessary to implement direct entry dictionary, or the RegexSwap at first.

**Comment by ClaudiaPHI** [comment]
Complete management of reference data.
