### ISSUE TITLE
Output options for analyse results

### ISSUE THREAD

**Issue by jelmerlas** [datacleaner/DataCleaner#1386]
Hi all,

I wanted to export results from some basic profiling. Wasn't able to export the detailed results from my pattern finder to CSV or Excel. Anyone else running into the same challenge?
Please let me know!

Jelmer

**Comment by jhorcicka** [comment]
Hi Jelmer, 

can you provide some additional information? 
a) Which version of DC did you use? 
b) What kind of export did you use? 
c) (Ideally) Can you provide the job file? (You can use "Customers" datastore instead of yours)
