### ISSUE TITLE
Installer makes .exe files for a Mac OS install

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#139]
Rather it should include the .sh scripts and maybe some kind of launcher for Mac OS

**Comment by ClaudiaPHI** [comment]
Is this issue still relevant ?

**Comment by kaspersorensen** [comment]
Hmm I doubt. We changed the installer for Mac in 2015 and this issue is from 2014. Let's close it.

**Comment by drexler42** [comment]
I installed 452 recently on my MAC - there was no issue. But if you like I can install it again on my MAC this evening. Then I can report back on it.
