### ISSUE TITLE
DC Monitor REST API to get jobs should return more information about the jobs

### ISSUE THREAD

**Issue by JoosjeBoon** [datacleaner/DataCleaner#1391]
The API to get available jobs (repository/{tenant}/jobs) returns a list of job names and path. However this information is not enough for smooth integration in DataHub. Additionally this (or another) API endpoint should return the following information:

1) Job metadata (the metadata-properties of the job as shown in the example below)
```
 <metadata-properties>
            <property name="Group">Person Enrichment</property>
            <property name="Category">Enrichment</property>
            <property name="CoordinatesX.GoldenRecords.person">154</property>
            <property name="CoordinatesY.GoldenRecords.person">77</property>
        </metadata-properties>
```

2) Job components list
A list of the component descriptors present in the job. E.g.
```
[
  {type: "transformer", descriptor: "NL Consumer Check", medatataProperties: [the metadata properties of the component]},
 {type: "transformer", descriptor: "NL Deceased Check", medatataProperties: [the metadata properties of the component]}
]
```

**Comment by ClaudiaPHI** [comment]
- consider new endpoint for each job

**Comment by LosD** [comment]
I guess something like `repository/{tenant}/jobs/{jobId}` should be good.

**Comment by JoosjeBoon** [comment]
Hey guys just adding my two cents. If you do it this way that means that a REST user is forced to know up front which job they want to use. The idea we had was to put some metadata inside the job like shown below: 

`<property name="Category">Enrichment</property>`

And then fetch all jobs and filter the ones belonging to this group. Otherwise we will have to do something with file names: e.g.: 

> enrichment.NLCC.analysis.xml

 Which we would like to avoid.

So I was expecting an additional endpoint more like: repository/{tenant}/jobs/metadata
Which returns something like:

`[
{filename: "job1.analysis.xml", name:"job1", metadata:{
Category: "Enrichment"
}},
{filename: "job2.analysis.xml", name:"job2", metadata:{
Category: "Onboarding"
}}
]`

**Comment by MennoB** [comment]
Two cents more.
Currently the method JobsFolderController.resultsFolderJson already returns some metadata on the jobs as a Map. I was thinking there could be a second endpoint in that class ("{tenant}/jobs/metadata", for example) which would do more or less the same thing, but would return more elaborate metadata on all the jobs in the job folder. That way we could easily filter out any of the jobs that would be relevant to us.

**Comment by LosD** [comment]
Hmmm.... Wouldn't it be better to then just make the jobs endpoint able to filter directly on the metadata?

For example something like `repository/{tenant}/jobs?category=enrichment` or `repository/{tenant}/jobs?metadata.category=enrichment` if we want to keep our options for other filters open.
