### ISSUE TITLE
parseInt in javascript filter return NaN for number starting with zero

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1408]
When I use a javascript filter with a function which executes the parseInt function, parseInt returns NaN for values like '010', while it should return 10 in such a case.

**Comment by ClaudiaPHI** [comment]
According to this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt  in the case of parseInt function we need to a radix in case the string begins with 0.  

![image](https://cloud.githubusercontent.com/assets/6339923/17430805/b5e4e316-5af6-11e6-82d7-ac8951857b5f.png)

**Comment by ClaudiaPHI** [comment]
The values Nan is correct if the string started with the letter 'O' and not the digit 0(zero).

**Comment by LosD** [comment]
Seems to work as it should. To be sure numbers are considered decimal, use `parseInt(numberToParse, 10)`

Reopen if still able to reproduce.
