### ISSUE TITLE
NullCheckFilter: out of bounds exception

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1423]
In a simple job with "orderdb", "null check filter" and "value distribution" I get "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0". 

![null-filter-oobe](https://cloud.githubusercontent.com/assets/13213915/16618243/a36843d4-4388-11e6-8b88-3e81d82f3a2f.png)

**Comment by LosD** [comment]
Only happens if you don't choose any columns in the value distribution component.

We should probably check that in the validate method.

**Comment by LosD** [comment]
It seems we do. I have "Something went wrong ... No input columns configured for Value distribution", but I'm still allowed to run the job.

**Comment by jhorcicka** [comment]
OK, I can confirm that (I tried that and had same result). So, the fix will be about disabling "execute" button when there is this error, right?

**Comment by LosD** [comment]
I think so, but maybe look in Git log too see when and why it is enabled. I'm 90% sure we _did_ block execution at some point.

**Comment by jhorcicka** [comment]
OK
