### ISSUE TITLE
Nullpointer in JobInvocationController.invokeJobMapped

### ISSUE THREAD

**Issue by MennoB** [datacleaner/DataCleaner#1428]
**Calling JobInvocationController.invokeJobMapped within 5 seconds after  JobsFolderController.getFolderJobsMetadataProperty leads to NullPointerException.**

Currently the method `JobsFolderController.getFolderJobsMetadataProperty` leads to the initialization of the `TenantContext` job cache `(TenantContextImpl.buildJobCache`), a cache that lives for 5 seconds. Subsequently that method calls the `DataCleanerJobContextImpl.getAnalysisJob` method, which sets the `_lastModifiedCache` field of each instance of that class to the last modified time stamp of the file.

If, right after this, `JobInvocationController.invokeJobMapped` is called, this calls `DataCleanerJobContextImpl.verifyJobMetadataCurrent`. However, this call fails to initialize the `_sourceColumnPaths` field for that class, because the `_lastModifiedCache` timestamp is already equal to the last modified time stamp of the job file. A subsequent retrieval of the `_sourceColumnPaths` field in the `JobInvocationController.invokeJobMapped` method results in a null value for that collection leading to a nullpointer.

**Comment by kaspersorensen** [comment]
No longer applicable to CE
