### ISSUE TITLE
Ability to assign labels to metrics in DC monitor timelines

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1439]
When I select metrics for timelines they typically have technical names based on the analyzer used and the type of metric that is selected (e.g. "Distinct Count (country)"). I would like to be able to assign labels to these metrics, so they are presented more nicely and can be fitted more to the user's understanding.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
