### ISSUE TITLE
Some countries are not recognized

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1443]
Some countries are not recognized by ContryStandardizerTransformer 

```
Congo, Democratic Republic of the
South Sudan
Macedonia, The Former Yugoslav Republic of
Burma
Congo, Republic of the
Kosovo
Bahamas, The
Gambia, The
Cayman Islands, The
East Timor
British Virgin Islands
Micronesia, Federated States of
Netherlands Antilles
Yugoslavia
St. Maarten
Wallis and Futuna
Holy See
Corsica
Gaza Strip
```

**Comment by LosD** [comment]
A lot of these are not current countries

**Comment by ClaudiaPHI** [comment]
I am checking all of them. Some actually are not in the country list such as South Sudan: https://www.iso.org/obp/ui/#iso:code:3166:SS

Others are not recognized because of <b>", The"</b> attached in the end. Eg: Bahamas, The

**Comment by LosD** [comment]
No, South Sudan is probably too new, that one definitely needs to be added. 

Others, like Yugoslavia doesn't exist anymore. 

We might want to add Burma, even though it is not officially the name anymore.
