### ISSUE TITLE
Component for splitting one row into multiple rows

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1444]
```
a,b,c => a\nb\nc
```

This is good for a set of checks that should be performed on multiple columns.

```
for column in Row[a,b,c]: checkA(column) & checkB(column) & checkC(column)
```

**Comment by LosD** [comment]
Not sure I understand the idea of this,  why can't you just use multiple components? In general we try to avoid components that split into multiple rows, so this seems a bit like going backwards. 

If it really does provide value, at least make it as a output datastream.

**Comment by jhorcicka** [comment]
I can use multiple components. But imagine that I need to check for example 5 columns. And each of them needs to be checked for a) containing number, b) containing special symbol, c) containing big letter, d) its length must be in a specified interval and ... 

Now, with "branches" (multiple components) I would have to manually (long, boring) create 5 times 4+ components and then I can decide to change something in every second component in a row... 

With this component I can create only one assembly/checking line and push all required columns from every row just by selecting their checkboxes. And when I want to update some configuration I have to do it only once at one place. 

Do you see my point, @LosD? I think it is a nice helper. If it is really bad idea from some point of view then just stop me. :-) (But I already have that implemented and I will use it personally, so I just won't push it into the master).

**Comment by LosD** [comment]
Hmmm, somehow yes, though I'd much rather find a way of taking out the pain of the first part than doing this.

Let's keep it separate for now (maybe on the extension swap?).

Is it done using output datastreams or is it adding rows into the outer scope?

**Comment by jhorcicka** [comment]
OK, I can put it into my personal github repository and we can use it as an extension. 

Sorry, I don't understand "datastreams" vs "rows in outer scope". I use 
```
    @Inject
    @Provided
    OutputRowCollector _outputRowCollector;
```
to do the trick.

**Comment by LosD** [comment]
If you implement the HasOutputDataStreams, it will create a new scope (actually a completely new inner job) where only the output from the component is available. That way other components in the outer scope doesn't get a nasty surprise where new rows suddenly show up.

One of the major problems with adding new rows to the current scope is that _all_ components are affected, even though the graph makes it seem like only the attached components are.

**Comment by jhorcicka** [comment]
Thanks for explanation/tip. It works with "HasOutputDataStreams", actually I extended MultiStreamComponent.

**Comment by jhorcicka** [comment]
I will put it into my personal repository so I assume I can close this issue here.
