### ISSUE TITLE
Hide(DeSelect) the Output Columns if the Transformer has Output Streams

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1451]
If a transformer implements HasOutputStreams, we want to keep the normal output columns for compatibility with the old jobs. 
However, for the normal Output Columns should be hidden.  

![image](https://cloud.githubusercontent.com/assets/6339923/16948860/6b020136-4db7-11e6-8c70-8239af5349c7.png)

**Comment by LosD** [comment]
Might be a bit extreme to do it for _all_ transformers with output data streams.

Can we make an annotation or something like that to trigger the hiding?

We might even want to not show them at all unless already connected in that case, if possible without too much problems.

**Comment by ClaudiaPHI** [comment]
I will make an annotation.
