### ISSUE TITLE
Removing already linked component can break job

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1470]
In some cases, when deleting a component whose output column has already been mapped to another column, then re-adding the same component again and mapping it to the same columns, _something_ gets confused.

### Steps to reproduce
1. Link an input column to a component
2. Link component to other component
3. Delete first component
4. Re-add component, and link it to the other component (using "Link to...") again.
5. Save and reload job.

### Expected outcome
Links fine, saves and reloads without issue

### Actual outcome
Either doesn't look like it is linked in the graph UI, or links the same column twice.
When opening job, it fails.

### Notes
The issue does not seem to be in "Link to...", but that the original component column links aren't deleted from the other component, which means the new component can/will be confused with the original. This makes it possibly related to #1339.

When the job is saved, it looks like the input column ids get a "2" attached, which is what breaks the loading. Part of the symptom might be from the fix to #1030 (I don't think that fix is wrong, though, it just exposes this issue).

We probably want to make sure that JaxbJobWriter refuses to save a job broken like this, instead of inventing ids for columns that doesn't exist.

### Workarounds
To avoid the issue, either delete the other component with the first, or make sure to manually remove the dangling references.

If you realize the job was broken when loading it, open it with an editor and look for input column ids that has a "2" attached in the end, without a corresponding output column, then remove the "2".

**Comment by LosD** [comment]
@ClaudiaPHI came with a nice theory that proved correct: If the target component (the one that is linked _to_ has its configuration dialog open, it _will_ update correctly. So this seems like the listener responsible of breaking links is somehow tied to the dialog instead of the actual background model.

**Comment by arjansh** [comment]
Typically widgets are registered as listeners and therefore when a property is changed (or a component containing a property is deleted) all open listening widgets are informed and update themselves and the underlying model accordingly. When a part of the model which depends on a property has no open widget it is thus not updated when such a property is changed.

Therefore it seems like a good idea to have these parts of the model listening too. This can however cause duplicate updates when the widget is open. So we might have to find some way around that.

**Comment by LosD** [comment]
If you can do _something_ to work around it fast, we might want to make a more proper fix soon.

I imagine getting completely rid of this two-way binding that is the core of a lot of our issues, and going to something like [Rx](https://github.com/ReactiveX/RxJava)
