### ISSUE TITLE
Make custom column naming configuration available to monitor

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1473]
#1472 makes it possible to configure custom column names for Excel, CSV and fixed-width datastores. It however only provides this functionality for the conf.xml and DataCleaner desktop. We should also make this functionality available to DataCleaner monitor, so you can add custom column names there.

**Comment by LosD** [comment]
Might be fixed by #1354

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
