### ISSUE TITLE
Group removal of components

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1500]
Duplicate of #312

When I select more components in the job graph and try to remove them by pressing "delete" key then sometimes it works but usually it does not. Selecting components one by one by a single click and then pressing "delete" works fine. 

Sometimes it seems that selecting another set of components followed by pressing "delete" helps but it is not a rule. 

![multiple-deletion](https://cloud.githubusercontent.com/assets/13213915/18437624/23bad5b0-78fe-11e6-8fa1-d7eef311ac7a.png)

**Comment by LosD** [comment]
Workaround: After selecting the components, click one of them before pressing [delete].

**Comment by jhorcicka** [comment]
For some reason the event is processed by SchemaTreePanel instead of JobGraphKeyListener.

**Comment by LosD** [comment]
:open_mouth: Okay, that's pretty weird.

**Comment by jhorcicka** [comment]
Apparently it is about "focus". I used SchemaTree to drag components from. When I use context menu instead, nothing happens from beginning.

**Comment by jhorcicka** [comment]
The more I google this problem the more I am getting "swing was not designed for this, use key binding instead".

**Comment by LosD** [comment]
Hmmm... That sounds a bit weird to me. If you use a global key binding, you'll still need to determine what the current context is (e.g. we dont want it to delete components while you're editing in the search field).

**Comment by jhorcicka** [comment]
https://docs.oracle.com/javase/tutorial/uiswing/misc/keybinding.html

I don't mean global bindings.

**Comment by LosD** [comment]
Ah, I misunderstood. Yeah that probably makes sense, though you'll probably still need to make sure that is really what we want; it seems to me that the general problem is that the graph is losing focus, not that we don't react when it doesn't have focus... I know we did some funky stuff to make the search field always active, maybe this is a sideeffect.

**Comment by LosD** [comment]
(of course, that doesn't change that we probably shouldn't use key listeners unless we really need it)

**Comment by jhorcicka** [comment]
Okay, key-binding variant works. I am going to investigate search-field anyway to understand it.

**Comment by jhorcicka** [comment]
I tried to remove _searchField completely from SchemaTreePanel and it did not help. It seems the problem with lost focus is somewhere else.
