### ISSUE TITLE
Monitor performance issues with many jobs

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1501]
The performance of the monitor seems to go down quite a bit when many jobs are registered. Especially just showing the scheduled page takes a long time, and adding an alert also seems to be very slow.

**Comment by LosD** [comment]
Added "Type: Bug", since it seems to become closer and closer to the point of unusable after 20-30 jobs.

**Comment by jhorcicka** [comment]
I tried to upload 50 copies of the same simple job (with different names):
**jobs count | time [ms]**
8  (default) | 521
18  | 854
28  | 1132
38  | 1377 
48  | 1420 
58  | 1511

**Comment by LosD** [comment]
Oh wow, that's one good reason to use Linux

Might be the memory settings being different, though... Maybe check that Tomcat have the same amount of available heap space.

**Comment by jhorcicka** [comment]
I asked @ClaudiaPHI to do the similar experiment on her machine and it came out with very similar results as on my Linux machine. So, I guess "windows-virtualbox" results are irrelevant here. 

On the other hand it means I didn't reproduce the issue. @LosD, can you provide me with those 20-30 jobs that made Monitor slow in your case? Or at least can you describe them in a way that could help me to create similar situation on my machine? For example number of different datastores and their size, complexity of jobs (number of components and their types), etc.

**Comment by LosD** [comment]
I found out their Tomcat max memory setting is 256MB... Might want to check if yours is the same (I think it's default, so there's a good chance).

Their jobs has a ton of components, as they are extracting discrete fields from text, and every extracted field requires a regex parser and a remove substring, that might make the memory pressure harder.
