### ISSUE TITLE
Unsaved timelines should autosave or warn the user when changing page.

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#1508]
It is very easy to forget saving the timelines. We should have a way to avoid users losing their work when browsing to other monitor pages.

A few suggestions for fixing (only use one, obviously :)):
- Always warn the user when changing the page.
- Save the timeline in the session, so that s/he can save it later.
- Save the timeline "for real", with an obviously temporary name.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
