### ISSUE TITLE
Monitor: unsuccessful upload of a file with spaces in its name

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1528]
When I try to upload a file with a name containing spaces, the upload goes fine but confirmation messages says "File upload was not successful". Without spaces it works fine (for the same job). 

![upload-unsuccessful](https://cloud.githubusercontent.com/assets/13213915/18864145/3cf7b41a-8495-11e6-86ed-bccbd90c7731.png)

**Comment by jhorcicka** [comment]
I will extend this issue with the following: when you upload "many" files together, the "success message" text overflows. 

![file-upload-success-too-many-files](https://cloud.githubusercontent.com/assets/13213915/18867065/04529b4e-84a3-11e6-838b-b45c9d4d538b.png)

It is quite related to the previous issue so I think they can be solved together.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
