### ISSUE TITLE
Make it more easy to configure tenant for monitor

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1537]
DataCleaner monitor by default uses the `demo` tenant, if you want to change this, you have to change an XML file inside the deployed web app, which will of course be overwritten if you redeploy the web app. Therefore it would be better if we could configure this in some other manner outside the web app, e.g. in the datacleaner-monitor.properties file.

**Comment by LosD** [comment]
Agreed. In general anything that makes it necessary to edit files inside the webapp needs to go.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
