### ISSUE TITLE
Make "demo account" box in monitor configurable

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1538]
As far as I can see, it's not possible to remove the "demo account" box from DataCleaner monitor's login screen without modifying the source code. You however don't want to see this box when making use of DataCleaner monitor outside the "demo" scope.

It should therefore be easy to remove without changing something inside the web app itself.

**Comment by LosD** [comment]
Doesn't the `monitor.ui.show.demo.accounts` in the monitor properties do exactly that?

**Comment by arjansh** [comment]
Nice, indeed it does.
