### ISSUE TITLE
Can not create poolable connection factory (socket creation error)

### ISSUE THREAD

**Issue by chandrin** [datacleaner/DataCleaner#156]
Happens when you register a new Hsqldb/HyperSQL file and you give a wrong datastore name, username or password
for example datastore name : test, username test, password : test

![screen shot 01-09-15 at 09 28 pm 001](https://cloud.githubusercontent.com/assets/9272941/5685919/7531f6b0-9847-11e4-8d52-f4218215dd64.PNG)

**Comment by chandrin** [comment]
Similar issue

![screen shot 01-10-15 at 10 38 am](https://cloud.githubusercontent.com/assets/9272941/5690948/6ce885ea-98b6-11e4-92b9-a63ac0307cf2.PNG)

**Comment by kaspersorensen** [comment]
In my opinion this is good behaviour. Shouldn't the application show the error details when the user has entered invalid connection information? Do you think it is a bug? Why?

**Comment by jhorcicka** [comment]
I don't consider this as an incorrect behaviour => closing this issue.
