### ISSUE TITLE
connection to localhost refused

### ISSUE THREAD

**Issue by chandrin** [datacleaner/DataCleaner#157]
Happened while i was trying to build a job with an existing datastore i created.
![screen shot 01-10-15 at 10 42 am](https://cloud.githubusercontent.com/assets/9272941/5690941/0d87b814-98b6-11e4-91fa-ea71c9a346fa.PNG)

**Comment by chandrin** [comment]
![screen shot 01-10-15 at 10 43 am](https://cloud.githubusercontent.com/assets/9272941/5690945/31f9c656-98b6-11e4-8fcc-ddc3a3473bab.PNG)

**Comment by kaspersorensen** [comment]
Hi @chandrin , I appreciate that you report all these issues. But in my opinion they aren't really bugs or anything like that. You will get error dialogs when you cannot succesfully connect to a datastore for whatever reason. That's a good thing. The user is told of what symptoms the application is seeing, but we can never know what circumstances cause these symptoms - it may be firewalls, proxies, invalid information or monkey users. Either way I think it's fine that the application is telling the user that what he did does not work.

**Comment by jhorcicka** [comment]
I don't consider this as an incorrect behaviour => closing this issue.
