### ISSUE TITLE
Have desktop's jobs tested by integration tests

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1577]
Jobs currently not available in Monitor by default but available in Desktop should be added into integration testing process. 

Relates to #1563

**Comment by jhorcicka** [comment]
What do you think about synchronization of Desktop's and Monitor's jobs (@arjansh, @LosD, @ClaudiaPHI)? This would be easier way to complete this task. Otherwise, if we don't want to introduce duplication/copies of the jobs, we have to introduce some approach how to get job files from desktop's package to monitor's package so that they are available during "verify" phase of the maven build.

**Comment by ClaudiaPHI** [comment]
First we need to separate the commercial jobs from the other jobs.

**Comment by LosD** [comment]
I _think_ I'd actually prefer them being executed by the CLI rather than the monitor... If for no other reason, then because we get that runner massaged as well.
