### ISSUE TITLE
Missing components' icons in a context menu

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1581]
In a context menu where you can select&add components to the job's graph there's a few items without an icon. 

![missing-icons](https://cloud.githubusercontent.com/assets/13213915/19651348/c8f4a82e-9a0c-11e6-888d-c37771acd3fe.png)

**Comment by ClaudiaPHI** [comment]
I have seen it for Round Number as well

![image](https://cloud.githubusercontent.com/assets/6339923/19676187/f2a8bd78-9a92-11e6-8511-04f7e9ad0399.png)

**Comment by ClaudiaPHI** [comment]
The bug appears in 5.1.3 and 5.1.2.
