### ISSUE TITLE
JobGraph: Support multiple OR'ed requirements (CompoundComponentRequirement)

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#159]
Make it possible to allow a single component to have multiple OR'ed component requirements.

This can already be done programmatically with the CompoundComponentRequirement.

 * Make sure that the graph rendering supports CompoundComponentRequirement. Each requirement should be shown as pointing to the target component.
 * Make it possible to add new OR'ed requirement via drawing a link in the graph.

**Comment by tomaszguzialek** [comment]
Continuing the discussion from PR #381, how to visualize OR component requirements. I think, just adding a label "OR" or "AND" next to the component with a compound requirement is enough. Introducing a special component for flow control (something like "join" node before the actual component) would mean we should introduce a "fork" node to keep it consistent. At the moment we just have multiple edges coming out of a component, so let's just have multiple edges coming in, but with a label to indicate if it is an "OR" or "AND" condition.

**Comment by kaspersorensen** [comment]
Where would you put the "OR" label? I mean, each edge is already individually labeled. Could also be that we use the icon to show a non-exclusive filter condition or whatever, I don't know.

**Comment by tomaszguzialek** [comment]
I would put the label on the target component (from the rendering point of view - next to the component) when there is more than one incoming edge.

**Comment by kaspersorensen** [comment]
![image](https://cloud.githubusercontent.com/assets/291450/7190706/48589350-e488-11e4-9834-b5dcd4c0d353.png)

So in this case ... same location as "String analyzer"?

**Comment by tomaszguzialek** [comment]
Yes, next to the infamous "A?" that confused me before :).

**Comment by kaspersorensen** [comment]
Hmmm .... But that's not the same place as the "String analyzer" label... And don't you think it is highly dependent on what angle the edges are coming in? My feeling is that one or more of the following are better approaches:

 * Use a different color for the (currently orange) icons on the edges
 * Add a new vertex representing the composite requirement (not happy about that one, but it's the most "pure" solution I can think of if we really aim for something sense-making).
 * Do nothing / keep like it is - this is not so sense-making but on the other hand it might be a matter of getting used to it.
 * Decorating the icon of the target vertex somehow but I am thinking we also do this when a component is invalidly configured and too many icon-decorations is also a bad thing.
