### ISSUE TITLE
DC monitor:  links are not rewritten 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1619]
Setup: 
Tomcat version 8.0.23
OS: OSX 

The following menu page links are not rewritten 
- Dashboard 
- Scheduling 
- Reference Data

![screen shot 2016-11-17 at 2 11 21 pm](https://cloud.githubusercontent.com/assets/6339923/20390588/eac6e086-accf-11e6-8893-ab925cfe8ed5.png)
![screen shot 2016-11-17 at 2 11 32 pm](https://cloud.githubusercontent.com/assets/6339923/20390645/1aaec12e-acd0-11e6-82e0-25867fd405e8.png)

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
