### ISSUE TITLE
DC Monitor: New timelines cannot be renamed 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1620]
Steps to reproduce: 

1. Create a new timeline 

2. Try to save it. 

The timeline cannot be renamed(saved). It get's the default name "new_timeline"

**Comment by ClaudiaPHI** [comment]
He problem was seen on Mac OSX and not reproduced again after restart of Tomcat.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
