### ISSUE TITLE
Salesforce Datatore:  Security Token Should be OPTIONAL

### ISSUE THREAD

**Issue by d416** [datacleaner/DataCleaner#1621]
Salesforce.com can be configured to NOT use security tokens - this is an administrative option and can be invoked for various reasons (e.g. if the org is locked down by IP address or Single Sign-on is set up)

Given that a) tokens are optional, and b) to generate a token requires a password reset,  the "Salesforce Security Token:" field on the Salesforce.com Datastore setup dialog box should be OPTIONAL.  Currently this field is required and prevents anyone without a token from authenticating.

**Comment by kaspersorensen** [comment]
Interesting point of view. We are leveraging Apache MetaModel for the connectivity to Salesforce. Could you maybe echo your request on the bugtracker for that? https://issues.apache.org/jira/browse/METAMODEL

**Comment by d416** [comment]
This issue is with the authentication layer, not the metadata, therefore the issue is with the DataCleaner code.... like basically this file line 116:
https://github.com/datacleaner/DataCleaner/blob/70e7978fe45dbbdd0cd307252d05a127ec1fdc51/desktop/ui/src/main/java/org/datacleaner/windows/SalesforceDatastoreDialog.java

**Comment by davkrause** [comment]
Noticed this from my emails today and started a pull reqest here: https://github.com/apache/metamodel/pull/143

**Comment by LosD** [comment]
Partially fixed by #1621; Allows the empty string as token.

Still needs a release (and integration, of course) containing apache/metamodel#143 for a full fix, where null tokens are also allowed.

**Comment by kaspersorensen** [comment]
Fixed as of DC CE 5.3.0
