### ISSUE TITLE
Automate code format checking and reformat entire codebase to follow

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#1622]
DC needs some automat checking of code format.

**Comment by LosD** [comment]
I guess we could look at either a Github plugin, something like checkstyle or some sort of commit hook.

I think I prefer the first, if possible, since both the others doesn't really become part of the review process.

**Comment by LosD** [comment]
I've taken the liberty of expanding this to also actually do something about the formatting.
