### ISSUE TITLE
Set maximal size for datastore overview dialog window

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1623]
1. Create a CSV file (or any other datastore) with more columns than can be viewed at once on your monitor (I had a 55 columns file). 
2. Create a job with this file as a datastore. 
3. Double click (not preview data) the datastore icon in the job graph. 

![too-large](https://cloud.githubusercontent.com/assets/13213915/20591651/0d37fcae-b22a-11e6-8e46-1ee5b91f5e4b.png)

**Comment by LosD** [comment]
Maximum sizes seems like a dangerous path, both fixed and calculated (the difference between windowing systems can be great). Any way to get the window to behave properly in another way?

**Comment by jhorcicka** [comment]
We (I) did the same for "Open as a template" dialog.

**Comment by LosD** [comment]
Okay. If no one ran into problems for that (sure it's sized correctly on all supported platforms?), I guess it's fine.

**Comment by jhorcicka** [comment]
I tested it on Linux and Windows. @ClaudiaPHI, could you please test it on Mac OS (if you haven't done that already)?
