### ISSUE TITLE
Create a hashing transformer

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1631]
The component should include all of the standard hashing algorithms and produce a hash and a length of the original data.

**Comment by jhorcicka** [comment]
Apart from (easily available at MessageDigest)
```
MD2, MD5, SHA, SHA-224, SHA-256, SHA-384, SHA-512
```
what algorithms do we want (@LosD, @arjansh)? 

```
CRC (16, 32), MD4, MD6, ... ?
```

**Comment by arjansh** [comment]
@jhorcicka Unless they're also easily available, I wouldn't add them up front.

**Comment by jhorcicka** [comment]
I added CRC32 (it was simple), the rest can be added when needed.

**Comment by LosD** [comment]
Having a CRC in there doesn't really make sense to me. It's not a hashing function, and not very widely used above protocol levels.

We don't really want to make the list the user has to choose between longer, just because we can.

**Comment by jhorcicka** [comment]
OK, I'll remove it then.
