### ISSUE TITLE
[PROPOSAL] Delete unused, non-CE and deprecated components and interfaces

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1753]
I would like to propose that the community edition of DataCleaner move forward in simplifying life for the community contributors by removing stuff from the project that anyways does not apply to community users:

* Backwards compatibility of deserializing legacy result files.
* Backwards compatibility for legacy components.
* Integration with the monitor application
* Integration with DataCloud

Maybe there are other things?

By getting rid of the components, we can make a proper cut in the code base and we would also be able to attract contributors more easily since there will be less "baggage" for them to carry around and worry about.

**Comment by LosD** [comment]
+1
