### ISSUE TITLE
Kafka datastore

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1794]
With the release of MetaModel 5.1.0, a new DataContext implementation is made available for querying Kafka streams. We should add a datastore in DataCleaner to take advantage of this functionality. That will enable us to be one of the few (only?) open source data quality tools that work with Apache Kafka!

**Comment by davkrause** [comment]
I just now notice this issue is here so I want to tell you that I am working on this feature. Currently have a branch ("kafka") in my mirror of Datacleaner. With the new apache metamodel version out, this branch should be working soon so you can inspect it.
