### ISSUE TITLE
documento

### ISSUE THREAD

**Issue by darkgalz** [datacleaner/DataCleaner#1795]
Tarea
[CARACTERIZACION_TAREA.docx](https://github.com/datacleaner/DataCleaner/files/2362318/CARACTERIZACION_TAREA.docx)

**Comment by LosD** [comment]
This looks rather suspicious. I've reported it to Github.

**Comment by kaspersorensen** [comment]
I agree. Looking at the document it seems to be a bunch of DC screenshots, but I have no context about why I should be seeing them.
Closing the issue.
