### ISSUE TITLE
DataCleaner-Monitor under SSL

### ISSUE THREAD

**Issue by akrathod71** [datacleaner/DataCleaner#1805]
Why does the style of the analysis job go away?  it looks different

**Comment by kaspersorensen** [comment]
Hi @akrathod71, I'm not sure what you're referring to. Probably an old release of DataCleaner monitor? We've stopped maintaining the monitor webapp in the community edition of DataCleaner, but I'm happy to give you my 5c based on the older releases ...

**Comment by akrathod71** [comment]
Hi Kasper, yes, i was using DataCleaner-Monitor v 3.7.2.  it works so why not?

if i run the application without SSL and then view the customer completeness report, there's a blue background.  if i run the application with SSL, the report shows but the formatting disappears.  i wasn't sure how to handle that.

i am handling it through a security constraint in the web.xml file
<security-constraint>
    <web-resource-collection>
         <web-resource-name>DataCleaner-monitor</web-resource-name>
         <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <user-data-constraint>
        <transport-guarantee>CONFIDENTIAL</transport-guarantee>
    </user-data-constraint>
</security-constraint>

**Comment by akrathod71** [comment]
`<security-constraint>
<web-resource-collection>
<web-resource-name>securedapp</web-resource-name>
<url-pattern>/*</url-pattern>
</web-resource-collection>
<user-data-constraint>
<transport-guarantee>CONFIDENTIAL</transport-guarantee>
</user-data-constraint>
</security-constraint>`

**Comment by kaspersorensen** [comment]
Can you check your browser's developer tools? My guess is that some of the resources are not resolved or are rejected by the browser if they are requested via HTTP instead of HTTPS. Usually browsers will not allow a page on HTTPS to include e.g. a HTTP based image.

**Comment by akrathod71** [comment]
is that something i can change code-wise using the browser's developer tools?  i'll give it a try

**Comment by kaspersorensen** [comment]
Let's first confirm if that's the problem. I'm not sure what the solution is, but figuring that out will be easier when we know the problem :)

**Comment by LosD** [comment]
Probably the style source is hardcoded with a `http://` prefix. Not sure if it can be worked around, though.

Maybe there's a way to add a filter to web.xml that could fix links before sending the finished HTML?

**Comment by akrathod71** [comment]
i will check this out and let you know.

**Comment by akrathod71** [comment]
so i turned on the developer tools in Firefox and got the following messages

- Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Ubuntu:400,500,700|Lobster|Open+Sans”

- Blocked loading mixed active content “http://eobjects.org/resources/datacleaner-html-rendering/analysis-result.js”

**Comment by akrathod71** [comment]
Got it!  i had to add another security-constraint to web.xml
`	<security-constraint>
	    <web-resource-collection>
	        <web-resource-name>DataCleaner-monitor</web-resource-name>
	        <url-pattern>/*</url-pattern>
	    </web-resource-collection>
	    <user-data-constraint>
	    	<transport-guarantee>CONFIDENTIAL</transport-guarantee>
	    </user-data-constraint>
	</security-constraint>
	<security-constraint>
        <web-resource-collection>
            <web-resource-name>eobjects.org/resources</web-resource-name>
	        <url-pattern>/*</url-pattern>
        </web-resource-collection>
        <user-data-constraint>
            <transport-guarantee>NONE</transport-guarantee>
        </user-data-constraint>
    </security-constraint>
`

**Comment by kaspersorensen** [comment]
Great! I guess we should (if we where still maintaining the project) add HTTPS to the google font URL. The eobjects.org URL should be replaced with some locally hosted JS file. I believe that was available in the commercial editions, but oh well.

I'm gonna mark this one as closed for now, but thanks for shedding light on this topic.

**Comment by akrathod71** [comment]
This has to be the most geeky thing i have ever figured out. So Kasper and Dan, my question to you is - this is clearly an old library.  Will this continue to be around?

**Comment by akrathod71** [comment]
never mind, you just answered the question.  i will buy the commercial version

**Comment by echumo** [comment]
> Great! I guess we should (if we where still maintaining the project) add HTTPS to the google font URL. The eobjects.org URL should be replaced with some locally hosted JS file. I believe that was available in the commercial editions, but oh well.
> 
> I'm gonna mark this one as closed for now, but thanks for shedding light on this topic.

Hi Kasper, I tried getting the commercial version but I got a 404. I understand that it was sold. Where can I get the commercial version?

**Comment by LosD** [comment]
Hi @echumo The commercial version is being sold by Human Inference. Try taking a look at https://www.humaninference.com/en/solutions/datacleaner

**Comment by echumo** [comment]
> Hi @echumo The commercial version is being sold by Human Inference. Try taking a look at https://www.humaninference.com/en/solutions/datacleaner

Thanks
