### ISSUE TITLE
Logging in Talend ESB

### ISSUE THREAD

**Issue by Bargavi2307** [datacleaner/DataCleaner#1819]

**Comment by LosD** [comment]
@kaspersorensen it seems to be spam. The link goes to some Talend training website. I have

**Comment by kaspersorensen** [comment]
Hmm I was able to mark it as spam. Doesn't seem like there's a delete option anymore, but there is an article that indicates that it was possible previously:
https://help.github.com/en/articles/deleting-an-issue

**Comment by LosD** [comment]
Well, the description is dead, which at least kills the SEO boost
