### ISSUE TITLE
The project can not be compiled successfully, please help to see the reasons, thank you very much!

### ISSUE THREAD

**Issue by winterbao** [datacleaner/DataCleaner#1821]
![image](https://user-images.githubusercontent.com/929719/56177651-f4e7b280-6031-11e9-8256-6320d8f5a825.png)

**Comment by LosD** [comment]
Does it also fail on the command line (`mvn install`)?

**Comment by winterbao** [comment]
Thanks a lot. But execute the [mvn install] stop at the location shown in the following image：

![image](https://user-images.githubusercontent.com/929719/56192624-6723bb80-6061-11e9-9c55-985192c71ec4.png)

**Comment by LosD** [comment]
I don't see any issue there. The SLF4J error message is just because, logging hasn't been configured for the build, it shouldn't break it.

**Comment by winterbao** [comment]
Thank you very much. The project can run. I want to connect mysql database, how to do it?
![image](https://user-images.githubusercontent.com/929719/56206922-13749a80-6080-11e9-8852-8c7fe41fb78e.png)

**Comment by LosD** [comment]
You will need to install the mysql JDBC driver first. I'm not near a computer at the moment, but there should be a datastores section in the settings, where you can install it.

**Comment by winterbao** [comment]
Is there any good way to solve the problem of Chinese display scrambling code?

**Comment by LosD** [comment]
I remember seeing the issue mentioned before. Try to do a search for it here (for some reason, Github doesn't seem to allow issue search on the mobile site)
