### ISSUE TITLE
Research Help

### ISSUE THREAD

**Issue by 19-08usc** [datacleaner/DataCleaner#1829]
Hello!

I'm a grad student at USC and I'm not at all familiar with open source software, but I have an assignment where I need to get some feedback about open source software, Data Cleaner, in particular. Would anyone here be willing to answer 6 quick questions?

I promise it doesn't take too long and it'll be tremendously helpful. 

I've included the questions below for your reference. 

1. Is the application cloud-based?
2. What file formats does the technology work with (e.g. . csv)?
3. What is the average skill-level of users?
4. What feedback have you heard from users regarding ease of use and overall effectiveness?  
5. What are the difficulties clients have when they use the platforms?
6. What are the specific resources that are most popular and useful to governments?

Please reach out to me if you have any additional questions or leads where I would be able to access this information or where to find the right folks to talk to. 

Thank you in advance!

**Comment by kaspersorensen** [comment]
Hi there,

1. No
2. There's a lot. CSV, Excel, MS Access, SAS, dBase, XML, JSON ... and always adding more
3. Requires knowledge of databases.
4. I think DC is generally considered very easy to get started with, but hard to become an expert in.
5. Complex workflows can be hard to manage. People often want to reuse workflows, which is possible but can make editing a workflow more risky.
6. I wouldn't know, you would have to ask a government :-)
