### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by arkid** [datacleaner/DataCleaner#1841]
Not sure if this is the best place to write them, if there is somewhere else please share as I would love for them to get to the right people.

1. Add a _preview_ function on all the write commands.   This is usually the end of an analysis workflow and it would be great to see what the end output is looking like after transformation etc.  Doing this right in the program with preview is going to be so much quicker than actually writing out to a file/database.

2. In the job analysis have a 'write' option that generates sql insert / update commands.  That would be incredibly useful for debugging as well as transporting the data to another system more manually. 

3. A _refresh_ option in the left side of the analysis interface where you select tables/columns from.  Sometimes I would be working on a database or underlying csv and alter them and these changes won't be reflected in the program unless you come all the way out of a job and go back in.

**Comment by kaspersorensen** [comment]
Hi @arkid 
Thanks for this great feedback. I think all three points are really good and valid!
Can you create three separate issues for them though? I think combining them all here makes it harder to track how we're going to fix each of them and what their status is etc. Thanks.
