### ISSUE TITLE
5.3.0 community edition not support Oracle？

### ISSUE THREAD

**Issue by yanqw** [datacleaner/DataCleaner#1842]
I pull the source code and start the desktop program to find that there is no Oracle connection option

**Comment by kaspersorensen** [comment]
Oracle's driver isn't open source so you'll have to download it yourself and then install it using the "Options" dialog (see https://datacleaner.github.io/docs/5.7.0/html/ch13s01.html)

PS: Why download version 5.3 and not the latest??

**Comment by yanqw** [comment]
Thank you very much, because someone has used version 5.3, tell me to use this
