### ISSUE TITLE
New Data Cleaner CommunityEdition user

### ISSUE THREAD

**Issue by Alio-hub** [datacleaner/DataCleaner#1846]
I want to start using the tool, so I wonder if you can guide me on how to start, is there is some kind of tutorials or training videos that can help me at the very beginning or anything to read?
I'd be glad about that.

**Comment by kaspersorensen** [comment]
Wish you a pleasant experience using DC. Going to https://datacleaner.github.io/documentation would be the central spot for you.

**Comment by Alio-hub** [comment]
thanks for that, i'll start playing with the tool and if there is any thing confusing i'll get back to you
