### ISSUE TITLE
Design idea of datacleaner

### ISSUE THREAD

**Issue by yanqw** [datacleaner/DataCleaner#1848]
Now I come across a project. Can you tell me if you want to learn from the design idea of datacleaner.

**Comment by kaspersorensen** [comment]
I don't understand the question?

**Comment by yanqw** [comment]
> I don't understand the question?
I want to know the design idea of datacleaner, because I can't run it locally, I can't know its running process

**Comment by kaspersorensen** [comment]
I'd argue that those are two very different things :) But whatever... The docs are here, and they contain some information about the general idea for the product: https://datacleaner.github.io/documentation

Regarding not being able to run it locally - try starting it up from the command line and report back if it comes back with any error messages.

**Comment by yanqw** [comment]
Maybe I did n’t describe my problem well. Thank you for your help. I will look at the document and try to find the answer.
