### ISSUE TITLE
PostgreSQL error: zero-length delimited identifier at or near "" ""

### ISSUE THREAD

**Issue by yanqw** [datacleaner/DataCleaner#1849]
When I connect to the postgresql database to analyze the data, I always report an error: zero-length delimited identifier at or near "" "", this is true for multiple versions of datacleaner

**Comment by kaspersorensen** [comment]
Hmm I haven't experienced that myself, but maybe you can double-check your connection string? Looks like there might be a whitespace in there that shouldn't be there.

**Comment by yanqw** [comment]
Not a problem with connection strings. When I use the client to connect, I can see the tables in the database, but this error still occurs during analysis.
![image](https://user-images.githubusercontent.com/48747336/76728562-04b3cd80-6792-11ea-8648-d67d3da48e10.png)

**Comment by kaspersorensen** [comment]
Can you tell me the name(s) of the table(s) you're analyzing? This looks a bit like a query gone wrong.

**Comment by yanqw** [comment]
When I debug the code with a breakpoint, I see that all the SQL statements are concatenated. For example, the statement obtained when connecting to postgresql is "SELECT APPROXIMATE COUNT (*) FROM." Bm_ks "", missing the schema name; and the connection The statement obtained when Oracle is "SELECT APPROXIMATE COUNT (*) FROM TA3." AA10 "", so the connection to Oracle can be analyzed normally. I don't know how to deal with the problems that occur here.

**Comment by lorena6017** [comment]
Hello, you already solved your problem, because the same thing happens to me and I don't know how to tackle this problem. thanks

**Comment by kaspersorensen** [comment]
That sounds like a query rewriting issue in Apache MetaModel (which I'm also involved in). I'll take a further look soon.

**Comment by yanqw** [comment]
The postgresql version I am currently using is 11.6, and I found that when I use the postgresql version 9.6.17, the above problem does not occur

**Comment by kaspersorensen** [comment]
Reproduced this as a MetaModel bug: https://issues.apache.org/jira/browse/METAMODEL-1224
