### ISSUE TITLE
Release Differences 

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1853]
Hello community,
I'm exploring DataCleaner. 
I'm running version 5.2 as that is the latest version available on Windows. However, I notice there is a 5.7 version which only appears to available on Linux.
Can you let me know if there are any features in 5.7 that aren't available on the windows release 5.2?

Thanks

Carlton

**Comment by LoLei** [comment]
You can find the differences each release introduces here:
https://github.com/datacleaner/DataCleaner/releases

But also, all releases after 5.2 are cross-platform, are they not? The zip file is centered between all operating systems [here](https://datacleaner.github.io/downloads), not in the Linux column.

**Comment by cpatte7372** [comment]
Thanks for reaching out.
I don't think I've made myself clear.

All the releases after 5.2 are for Linux, not Windows.. I was wondering if the releases after 5.2 are also for Windows?

**Comment by LosD** [comment]
All the releases after 5.2 are cross-platform, as there is no longer a platform-dependent runner. Just use Java to run it.
