### ISSUE TITLE
Purchase the Professional Edition

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1855]
Hello Community,

I am evaluating Datacleaner using the Community Edition. However, there are functions like Duplicate Detection and Merge Duplicates that appear to only be available with the commercial edition.

Can someone let me know how to go about obtaining an trial key that will enable those functions, alternatively let me know how to go about purchasing the Professional/Commercial edition?

Thanks
Carlton

**Comment by LosD** [comment]
Hi Carlton, you should be able to get a trial or purchase it from Human Inference here: https://www.humaninference.com/en/solutions/datacleaner

**Comment by cpatte7372** [comment]
Hi LosD,

Thanks again for reaching out. 

I have already submitted a request at the link you provided above.

I guess I just have to wait - I thought I would automatically be sent a link for the trial, but I guess someone needs to physically approve.

Hopefully, I'll get the trial very soon,.

Cheers

**Comment by LosD** [comment]
I don't really have anything to do with the commercial product, but maybe @arjansh can help speed it up.

**Comment by arjansh** [comment]
Hi Carlton,

Requests submitted from https://www.humaninference.com/en/solutions/datacleaner aren't handled automatically, I expect you'll receive your trial somewhere today, I'll remind the person who's responsible for handling the trial requests.
