### ISSUE TITLE
Email Correction with DataCleaner

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1856]
Hello in the YouTube demonstration https://youtu.be/eIpmscL0qj8 there is function called Email Correction. Can you let know if the function is available in Community Edition? As I can't see the function.

Cheers

Carlton

**Comment by LosD** [comment]
The email correction is not in the community edition. However, if you just need basic "is this address following the email format rules?", a simple regex filter should work.

**Comment by cpatte7372** [comment]
Hi LosD,

I agree, the RegEx filter is great for now.
I look forward to getting receiving the trial key for the commercial edition.
