### ISSUE TITLE
Unable ro Run Datacleaner Professional Edition

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1857]
Hello Support,

I have kindly been provided with a link to the DataCleaner Professional Edition for evaluation. I have successfully installed the application, however when I run the DataCleaner.exe I get the error messages

Error:Could not create the Java Virtual Machine
Error: A fatal exception has occurred: Program will exit

When I try to run DataCleaner.jar nothing appears.

Do you think the problem might be because I originally installed the Community Edition?

Regards

**Comment by kaspersorensen** [comment]
Please refer to Human Inference's support for commercial editions of DC.
