### ISSUE TITLE
Struggling Connecting to SQL Server as the DataStop

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1858]
Hello Community,
I'm currently evaluating Datacleaner and I'm trying to connect to SQLServer as a DataStore. 
I have followed the instructions when in the manual to connect to MS SQL Server using JDBC string as follows:
jdbc:jtds:sqlserver://MSSQLSERVER01/PrestigeCars;useUnicode=true;characterEncoding=UTF-8;useLobs=false

However, whenever I test the connetion I keep on getting the following error message:

Cannot create PoolableConnectionFactory (Unknown server host name 'MSSQLSERVER01'.)

Unknown server host name 'MSSQLSERVER01'.

MSSQLSERVER01

However, the server is fully functional.

Any thoughts?

Cheers

**Comment by kaspersorensen** [comment]
Is `MSSQLSERVER01` a valid host name? Can you for example ping it via command line?
```
> ping MSSQLSERVER01
```

**Comment by cpatte7372** [comment]
Hi Kaspersorenson,

Thanks for reaching out.
I was able to resolve this issue from the following link:

https://stackoverflow.com/questions/6356612/jtds-driver-not-working-for-sql-server-2008r2-and-denali-native-sspi-library-not
