### ISSUE TITLE
Ready to Purchase Professional Edition

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1862]
Hello Community,

After spending the past month evaluating DataCleaner, I have reached out to Support, requesting a desire the purchase the full license. 

Unfortunately, after waiting almost two days I still havent received any response from the sales team.

Can someone let me know who I need to contact to enquire about pricing and the process to purchase the full license?

Thanks

Carlton

**Comment by arjansh** [comment]
Hi Carlton,

I'm sorry to hear that. I'll check with the people responsible for handling these requests if they received it, so they can respond to you.

Kind Regards,
Arjan Seijkens

**Comment by cpatte7372** [comment]
Thanks Arjan,

Marc Kliffen got in touch this morning.

Cheers
