### ISSUE TITLE
Data Cleaner Single User License

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1863]
Hello Community,

Marc Kliffen from Human Inference got in touch today to let me know how much a DataCleaner Enterprise Edition perpetual license costs. I won't announce the cost here, but lets say it was 100X more than I expected.

TBH, I wasn't seeking the license cost of an Enterprise Edition, I was hoping to get the cost of a single user license for the the Professional Edition, as there is no way I could afford the Enterprise Edition.

I have reached out to Marc again, but unfortunately it takes quite some time before they get back in touch. I have attempted to call Marc on the number he provided in his email, but with no luck.

Therefore, I was wondering if someone from here knows if there is a single user license for the Professional Edition?

Regards

Carlton

**Comment by kaspersorensen** [comment]
Hi Carlton,

This is not the place to ask TBH. Human Inference has commercial editions of DataCleaner, but the community open source edition (which this issue tracker is for) is completely independently managed and overseen primarily by volunteers that are not employed at HI.
