### ISSUE TITLE
DataCleaner Template Jobs

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1864]
Hello Community,

Is there a list of template jobs for Datacleaner on GitHub?

For example Datacleaner comes with a list of prepared jobs that we could use, see image.

However, I was wondering if there was a repository where more template jobs can be located?

<img width="304" alt="datacleanerjobs" src="https://user-images.githubusercontent.com/24607961/85180299-ff778a80-b27a-11ea-800c-612e62f06f69.png">

**Comment by kaspersorensen** [comment]
Yes, those jobs are located in this repo - in the folder [desktop/ui/src/main/resources/datacleaner-home/jobs](https://github.com/datacleaner/DataCleaner/tree/master/desktop/ui/src/main/resources/datacleaner-home/jobs).
