### ISSUE TITLE
Publish Reports to HTML/ IIS

### ISSUE THREAD

**Issue by cpatte7372** [datacleaner/DataCleaner#1865]
Hello Community,

Can someone let me know where I'm getting the following error when I attempt to publish reports to my IIS server, and how to resolve the issue?

![report](https://user-images.githubusercontent.com/24607961/85952345-848c2f00-b960-11ea-8c20-e51c85f5bbd3.png)

**Comment by kaspersorensen** [comment]
Hi @cpatte7372,

I think this is a misunderstanding. The publish option is built to work with the DataCleaner monitor webapp, which is not part of the community edition. You cannot publish just to any HTTP server like IIS.
