### ISSUE TITLE
Can Community Edition support Windows Server 2012

### ISSUE THREAD

**Issue by cheongww** [datacleaner/DataCleaner#1869]
Hi. I received an error message when opening DataCleaner.exe which is "Exception in thread "main" java.lang.UnsupportedClassVersionError: org/dataclean er/Main : Unsupported major.minor version 52.0".  
I have been using CE version in my laptop Windows 10 without any problem.

Thus I am thinking whether or not DataCleaner SE supports OS Windows Server 2012.
Thanks, WW.

**Comment by kaspersorensen** [comment]
The version that it is complaining about here is your Java runtime environment. You need to upgrade the version of Java on your machine.
