### ISSUE TITLE
Adding custom data store to GUI

### ISSUE THREAD

**Issue by jsx-gh** [datacleaner/DataCleaner#1874]
I implemented a custom data store by following the steps in the [blog post](http://kasper.eobjects.org/2012/04/implementing-custom-datastore-in.html) and it works fine. However, to create a new instance of the custom data store or reconfigure it, I always have to edit the config file. It there an easy way to make this available in the Data Cleaner GUI?

**Comment by kaspersorensen** [comment]
Unfortunately we do not have a hook for that, so you can only do it by incorporating it into the DataCleaner UI codebase. If the datastore type is generally useful, maybe you can contribute it?

You can find examples of datastore dialogs in the `org.datacleaner.windows` package -
https://github.com/datacleaner/DataCleaner/tree/master/desktop/ui/src/main/java/org/datacleaner/windows

**Comment by jsx-gh** [comment]
Thank you for the answer. We are still in a prototype stage and will therefore live with editing the configuration for the time being. We will consider publishing the data store once we are done
