### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by ryanbeymer** [datacleaner/DataCleaner#1878]
Might not be the right place but I can't seem to find out where pricing or how to get a commercial license. Does anybody know?

**Comment by kaspersorensen** [comment]
Offered by Human Inference - https://www.humaninference.com/

**Comment by ryanbeymer** [comment]
Thanks but they have been unresponsive. I found talend and that seems to be working for me.

**Comment by kaspersorensen** [comment]
Thanks for sharing @ryanbeymer. That's unfortunate for Human Inference. But maybe their business model has shifted. The open source community has some colleagues and ex-colleagues (like myself) of HI, but it is not associated with the company in any direct way anymore.

**Comment by ryanbeymer** [comment]
Yeah... I get that, i just wish they would open source the whole feature set then.
