### ISSUE TITLE
How may I add new columns and constants/default values to my target excel spreadsheet file?

### ISSUE THREAD

**Issue by ruben-jardim** [datacleaner/DataCleaner#1939]
My source file has 2 columns:
1. 'ID'
2. 'jobTitle'

But my new target file has 5 columns:
1. 'ID'
2. 'jobTitle'
3. copy of jobTile's value, but the column should be called 'UK_jobTitle'
4. copy of jobTile's value, but the column should be called 'global_jobTitle'
5. column 'status' which should be default as "A"

Therefore, how do I add 3 extra columns to my new target file, where:
- the first 2 new columns should have the same value as jobTile (but with different name)
- the last column needs a constant/default value as "A"

I checked the documentation, but unless I missed something there or in the discussion topics, I couldn't find how to do it, unless this isn't a functionality and I'm supposed to implement a workaround with the existing resources.

Thanks in advance.

**Comment by kaspersorensen** [comment]
Hi @ruben-jardim 
You need to somehow "generate" these values. For example you could use the JavaScript transformer to create new fields.
