### ISSUE TITLE
How can I change the type of a csv file in DataCleaner?

### ISSUE THREAD

**Issue by viardot** [datacleaner/DataCleaner#1946]
I have a csv file with the data:

firstname,lastname,phone,email,attendence,date
all,bundy,123,all@bundy.com,false,1-1-2000

After I load the data into DataCleaner and I want to do a boolean analyze or a date analyze the application tells me there is no boolean column and there is no date column. All columns can be processed as strings. Looking into the job xml I can see that all variable types are STRING.

    <column id="col_firstname" path="firstname" type="STRING"/>
    <column id="col_lastname" path="lastname" type="STRING"/>
    <column id="col_phone" path="phone" type="STRING"/>
    <column id="col_email" path="email" type="STRING"/>
    <column id="col_attendence" path="attendence" type="STRING"/>
    <column id="col_date" path="date" type="STRING"/> 
Changing it to BOOLEAN or DATE doesn't help.

I can't see an option in the UI nor a description in the help files of the application.

Does anyone know how to change the type of a column?

**Comment by kaspersorensen** [comment]
You can apply the "Convert to boolean" transformer.
