### ISSUE TITLE
How to allocate more memory to DataCleaner

### ISSUE THREAD

**Issue by VallieresF** [datacleaner/DataCleaner#1948]
Hi,
Is is possible to allocate more memory to DataCleaner? In the menu More/Options/Memory, i can see the memory available, allocated, used and free but I can't edit. I verify in the conf.xml file, but I don't see any information about memory.
Thanks!

**Comment by kaspersorensen** [comment]
You'll have to look at the .cmd or .sh file for DataCleaner then, and add more memory as per your JVM command line.
