### ISSUE TITLE
Add datastore dialog with table preview flickers while typing

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#195]
The examples are CSVDatastoreDialog and FixedWidthDatastoreDialog.

Steps to reproduce:
1) Choose a file (important to set pass the validation)
2) Type in the datastore name text field

The dialog flickers while typing, probably because of the time-consuming preview generation during every refresh.

**Comment by jhorcicka** [comment]
Not valid anymore => probably fixed within another issue.
