### ISSUE TITLE
SAS library datastore dialog has an dangling label

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#196]
Add / edit datastore dialog for SAS library has a "Tables:" label that is not associated with any input field. Should be removed or the missing input should be introduced.

**Comment by kaspersorensen** [comment]
Hmm yes the dialog works a bit poorly. You're supposed to select a directory, not a file.

When that's done the "tables" label will show like this:

![image](https://cloud.githubusercontent.com/assets/291450/5923597/ff078d76-a654-11e4-85e0-b42e759d8547.png)

But I am not sure that's very intuitive (or rather - it's not) ... Maybe remove the label and instead just post the text as a confirmation thingie...?

**Comment by tomaszguzialek** [comment]
Oh, it makes sense now, but still misleading. What about the initial text before choosing the directory? "Tables:      Choose the directory to infer the tables" or similar.

**Comment by kaspersorensen** [comment]
yeah that would be nice.
