### ISSUE TITLE
Getting data type, domain, non-null, null, unique, distinct, min, median, max

### ISSUE THREAD

**Issue by dukeofwagner** [datacleaner/DataCleaner#1967]
Is there a way to provide detail on data type, domain, non-null, null, unique, distinct, min, median, max?

**Comment by kaspersorensen** [comment]
Yes, use Number analyzer, String analyzer, Date analyzer etc.

**Comment by dukeofwagner** [comment]
Thank You.  Is there a way to export the results directly to .csv or .xlsx?

**Comment by kaspersorensen** [comment]
Not exactly. You can copy/paste the tables with data of course. I don't recall entirely, but I think the CLI also has an output format option where it exports metrics to CSV. But then you need to run the job from command line.
