### ISSUE TITLE
Property widget for mapped enums easily mess up the order of enums

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#203]
If I have a scenario like this:

![image](https://cloud.githubusercontent.com/assets/291450/5974004/6f5accde-a86f-11e4-8bca-94d61f1c3aa1.png)

And I then uncheck e.g. the "Posttown" column then it ends up "moving the selected enums down", messing up my mapping:

![image](https://cloud.githubusercontent.com/assets/291450/5974013/8af3e728-a86f-11e4-9c50-78d70b41c4c2.png)

And if I then re-check the posttown column it is once again in a even new strange mapping:

![image](https://cloud.githubusercontent.com/assets/291450/5974018/9fc37a24-a86f-11e4-812b-2dd23514d03b.png)

Involved class: MultipleMappedEnumsPropertyWidget

**Comment by tomaszguzialek** [comment]
Not even a one-liner, it was a one-worder, so merged it already without a PR ;).
