### ISSUE TITLE
Add "Clear all" button - graph UI

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#210]
I would like to be able to clear the Graph UI panel , to delete everything I have added it.

**Comment by kaspersorensen** [comment]
Could we rephrase as being able to select some/all components and then click DELETE to remove everything that's selected? I doubt this need is so usual that we want a more targeted function/visible option?

**Comment by ClaudiaPHI** [comment]
Yep. I think it is better your way.

**Comment by kaspersorensen** [comment]
OK then I will close this issue and refer to  #307 instead as it achives the same thing.
