### ISSUE TITLE
Component catalog should show up in the tree to the left

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#215]
Multiple user interviews have revealed that people would like to see the component catalog in the tree to the left side of the canvas. This is because then they don't need to dig into the menus to find them - the tree is shown continuously and always available. Furthermore it will lend itself to drag'n'drop behaviour when adding components, which would be nice and natural.

**Comment by LosD** [comment]
Please see #235 for problem to avoid.
