### ISSUE TITLE
Cannot connect source and a component in the graph UI.

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#219]
Steps to reproduce:
1) Choose the default "orderdb" datastore.
2) Add "Customers" table to the canvas
3) Add "String analyzer" to the canvas
4) Try to right-click the source -> "Link to..." and draw a line to the "String analyzer". It should connect the components, but the connection is not made.

This routine works on a different datastore ("contactdata.txt"), but does not work on "orderdb".

**Comment by kaspersorensen** [comment]
I saw the same thing happen with a postgresql database table which had the first couple of columns as INTEGER type. Maybe it has to do with the column types ...
