### ISSUE TITLE
Output DataSet producers and jobs

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#224]
Today one of the limitations to the compositional power of DataCleaner is that a job's data stream always ends when an analyzer is used. This is because the analyzer is performing an aggregate function on the dataset and as such it cannot produce records in the same cardinality as the input. We do have a couple of use cases where an aggregate function + further post-processing is necesary though:

 * Sorting data
 * Using a batch-based remote/web service for data transformation
  * Will typically require sending off the whole dataset and then wait for a result. Once the result comes back the stream in DC is out of scope.
 * Deduplication
  * Typically a duplicate detection component would detect duplicate records / pairs / groups (3 different output datasets).
  * A succeeding merging component would consume those records and produce merged records.

We want to make this possible so that we can model larger logical flows in DataCleaner.

From a XML spec standpoint, here's a draft example (using the deduplication scenario because that's the most complex one):

```
<analysis-job>
<source>
  <column name="person_id" id="id" />
  <column name="Full name" id="fullname" />
  <column name="Age" id="age" />
</source>
<analyzer descriptor="Duplicate detection">
  <input ref="fullname" />
  <input ref="age" />
  <output-dataset id="PAIRS" name="Pairs">
    <analysis-job>
      <source>
         <column name="RecordID1" id="id1" />
         <column name="RecordID2" id="id2" />
         <column name="Score" id="score" />
      </source>
      ...
    </analysis-job>
  </output-dataset>
  <output-dataset id="RECORDS" name="Records">
    ...
  </output-dataset>
</analyzer>
</analysis-job>
```

Things to notice:

 * The analyzer can have multiple output-datasets
 * In the output-dataset we can introduce a completely new analysis job.
 * The column definitions and references in the output-dataset's job are completely separate from the outer analysis job. In fact, they should also not have any way to access the outer data stream because the scope and granularity will not have any direct connection.

**Comment by kaspersorensen** [comment]
Some random thoughts on this ...

Designing a good interface for components that produce output datasets is a bit of a challenge. I can imagine that they would need at least to implement a method that provides metadata (column names, types etc.) for the OutputDataSet:

```
public OutputDataSetMetadata getOutputDataSetMetadata()
```

this metadata object would essentially contain one or more metamodel Tables. Why Table? Because if we want to reuse AnalysisJob and all that comes with it (builders and stuff) then we at some point need Column objects and so on too. So I think something like this would make sense (but probably not exhaustive):

```
interface OutputDataSetMetadata {
  public Table[] getTables();
}
```

Now to the part of publishing the records of these tables. The thing that is hard to say here is whether that should be push-based or pull-based. Push based would essentially be easier, it could basically be a simple addition of a table as a "target qualifier" to the existing OutputRowCollector interface:

```
@Provided OutputRowCollector outputRowCollector;

// in either run/transform/filter/getResult method:
outputRowCollector.putValues(targetTable, new Object[] { ... });
```

But pull-based is a lot easier to manage if we want to support optimizations such as:

 * Omitting output datasets that have no consumers in a particular job (probably pretty common, so I think this optimization is pretty important).
 * Allowing query optimization (e.g. Filter push down stuff such as a Max rows filter) in the consuming analysis job (probably pretty complex, so I consider it less important but nice to allow at least from an API point of view).

That could basically look like a metamodel query-like method on the component's interface:
```
public DataSet provideOutputDataSet(Query q);
```
To implement this method we could provide a few simple utilities leveraging MetaModel's query engine to provide the table data in various ways. The component could also have stored the data temporarily and simply serve this query by using a normal MetaModel DataContext.

It would be convenient in the pull-based approach also to have some way as a component to know if an output dataset is ever consumed or not. That may save time during the execution of the job if certain steps can be omitted.

The downside of pull based is that then it becomes hard to implement anything that is streaming - which would be great for performance when it is possible. Could we do both?

**Comment by manuelvandenberg** [comment]
Just a few random thoughts on this.

### Chaining vs nesting
When you introduce new analysis jobs in the <output-dataset> element, then you're essentially nesting job rather than chaining them. That feels conceptually strange. 
What I would expect is an analysis job to consists of several analysis job parts, each of these parts working on a single 'record stream' and having a defined input structure and defined output structure. These can subsequently be glued together in the analysis job. 
Treated in this way, there is an overlap with the 'nested job' idea.

### Optimizing execution
AFAIK, analyzers need to process the entire incoming data stream before producing any output. They keep track of the analysis output, either in memory or by using temp files on disk. So for all practical purposes, one could consider the analyzer as a datastore that can be queried. That would save time to store the data again outside of the analyzer context. 
Luckily, when writing this, I wasn't held back by extensive knowledge of the DC & MM internals :-)

**Comment by kaspersorensen** [comment]
Thank you @manuelvandenberg for the remarks. Let me see if I can process this :-)

On the chaining/nesting topic - I think you're right, conceptually we should think in a chaining metaphor. At the same time there is usually a pretty big push for backwards-compatibility (meaning that "simple" jobs that used to work should work in the same way going forward) which means that I doubt we can change the top level elements of the .analysis.xml format. Or maybe we can somehow do that but I am not seeing the light yet. For instance, maybe we could simply allow multiple <source> elements. *thinking*.

On the execution style of analyzers - you're right, but I had in mind to try and lax that fact a bit because I've seen a few case where it may not be necesary. And building up storage is very expensive if you can instead just directly pass on the data to the next component. I even didn't even necesarily think that this "output data" story should be restricted to just analyzers. For instance, maybe something like a transformer could output some records of a completely alternative format as "extra information" from it's operations. For instance having a date parser output a Date in the main stream and a String in the stream for "unparseable" date strings ;-)

**Comment by manuelvandenberg** [comment]
Agreed that backward compatibility is a great thing here and we should not loose that. If the job format has some kind of version indicator and conversion of an old job to the new format (becoming a single-melon-job) is possible, then we're covered.

Maybe I'm going to complicate matters, but I tried to take another angle on the melon jobs thing:
If one creates a transformer or an analyzer in DC (both henceforth called component), the interface of the component is defined using (reflection and) annotations. Roughly, the interface definition of any component has three components:
* input structure
* output structure
* parameters
In today's DC, an analysis job doesn't really follow this structure (AFAIK at least). We have "job templates" which might be the closest parallel.  If we could in some way have jobs follow the same interface definition (or a subset of it), then we would have the following advantages:
* nested jobs become a first class citizen;
* a melon job would be an analysis job with multiple job parts, and a 'mapping' part linking the parts together;
* one could even create a melon job where job parts are read from another XML file.
The essential thought here would be to place an analysis job (or job part) under the same abstraction as a component.


Then on the execution style of analyzers:  I understand the idea. I think it lines up with the earlier idea to have a transformer track and emit statistics when done. That makes it (at least partially) behave like an analyzer, and would make the stats a connection point for another melon. Correct?
But wouldn't that make implementing a transformer much more complex?
I don't really see the point of moving unparseable dates to a separate stream – or was that sarcasm?

**Comment by kaspersorensen** [comment]
We do allow currently to run another job as a component, using the "Invoke child job" component. But it comes with some simplification because jobs can do stuff that components cannot do - mainly they can split up the workflow using multiple filters, resulting in record s"traveling" to different destinations. A component (currently) on the other hand has a defined output structure whereas the different destinations in a job means that a job will have a superset of all output structures, where some of the output structure will only be available for some records. For instance if you have a filter F and two transformers T1 and T2, then the following graph would produce different output depending on the filter outcomes on given records:
```
            T1 -> dest1
          /
src -> F 
          \
            T2 -> dest2
```
Anyways, that was a long way to say that mapping here is quite complex and dynamic, making nesting a bit easier to manage as compared to chaining. This is largely easy on the input side, but hard on the output side because of the multiplicity of destinations. But the ability to read the melon job from another .analysis.xml file would be entirely doable in either approach - as long as the other job's input mapping matches the output dataset's metadata.

You're right about the stats example. And in fact Transformers can now effectively also create results/reports just like analyzers, so the only difference is that a transformer immediately returns something into the data stream whereas an analyzer does not - it has a "void" row consumption method.

The unparseable dates example was only partially sarcastic. Imagine that you would like a "true" date in one "success" stream (and maybe additional details, say "age" if it was a birthdate or something like that) and then in the "reject" stream you might just want the input back, maybe with an error message. So that means in the first stream the error message would not be there, but in the second stream the age would not be there.
