### ISSUE TITLE
Extension list buttons gets hidden by errors in extension

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#234]
If an installed extension fails (and the path is long enough), the dialog will hide the remove and website buttons. This is mostly cosmetic... _unless_ the user does not know that s/he can remove the extension by expanding the window.

![image](https://cloud.githubusercontent.com/assets/1282832/6147254/ba7f2e64-b1f5-11e4-8a5d-928dfa740661.png)

**Comment by jhorcicka** [comment]
Not valid anymore. 

![long_name](https://cloud.githubusercontent.com/assets/13213915/18385135/09cd1026-768f-11e6-82a8-a4d1486b76cf.png)
