### ISSUE TITLE
Error while mapping enum to columns

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#249]
When one tries to map an enum to columns using "Select All" option we get an error. 

![image](https://cloud.githubusercontent.com/assets/6339923/6189671/c19fd84e-b39c-11e4-9d26-cc1826e0a697.png)

**Comment by kaspersorensen** [comment]
Ready for review: https://github.com/datacleaner/DataCleaner/pull/254
