### ISSUE TITLE
EasyDQ has not been completely removed

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#260]
![image](https://cloud.githubusercontent.com/assets/6339923/6227423/d45e577a-b69f-11e4-8a9b-1c40b6e32eb2.png)

![image](https://cloud.githubusercontent.com/assets/6339923/6227425/e0e1c626-b69f-11e4-8f61-90949ca234ea.png)

**Comment by kaspersorensen** [comment]
This is known and accepted ... Our goal was not to remove EasyDQ _as such_ since it still exists. We just want to tone down the branding so that the component names are focused on function and not on brand (ie. "Email Correction" instead of "EasyDQ Email cleansing").
