### ISSUE TITLE
Synonyms dialog windows is too small and therefore hides edit/delete button

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#262]
The synonym configuration dialog (More | Synonyms) start with decent size, but edit/remove buttons for existing ones are hidden (if the path for the registered synonym catalog is long). 
![image](https://cloud.githubusercontent.com/assets/1483194/6227965/487b6c50-b6a6-11e4-9a43-bebf4c207d3c.png)

**Comment by jhorcicka** [comment]
Not valid anymore.
