### ISSUE TITLE
Sort column selection is empty when creating CSV file via schema-tree right click

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#265]
If I right-click on a table in the schema-tree and select "Write as CSV file" then I get the dialog with writing options. But for some reason the sort column selection is not giving me any options.

**Comment by ClaudiaPHI** [comment]
The problem is that there are no source columns in the job. If we add the table to the canvas, then we will have columns to sort on.

**Comment by kaspersorensen** [comment]
But the popup that is shown should not be using the active AnalysisJobBuilder instance, because that might already contain totally different components. Rather activating the popup should create a new job so that we do not mix up the things.

**Comment by ClaudiaPHI** [comment]
I cannot reproduce it anymore. I see no problems now.

**Comment by kaspersorensen** [comment]
Me neither, let's close it!
