### ISSUE TITLE
Datastore management needs to be improved 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#284]
In the existing datastore:
- we do not see a <b>scrollbar</b>. The panel itself doesn't have a scrollbar and it is hard to figure it out that you have to scroll down the window scrollbar to see the rest of the datastores. The first reaction is to think the file is not in the existing datastore list. It is not intuitive enough.
- the icons could be smaller
- the panel seems to have a fixed size. It doesn't resize to the right if the name of the datastore is long. Instead we have the icon on one row and the text on the other.

**Comment by kaspersorensen** [comment]
Sorry, but this is all made by design. It does not need to be improved, someone might want it different but there is always a thousand opinions of things and this is good enough for now.
