### ISSUE TITLE
The CSV and Excel files are not saved in the default datastore location

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#285]
The CSV and Excel files are not saved in the default datastore chosen by the user.

**Comment by kaspersorensen** [comment]
I don't know what this means?

**Comment by kaspersorensen** [comment]
Aaah, datastore __location/folder__.

**Comment by kaspersorensen** [comment]
A little remark for the fix: The datastore location can be extracted from UserPreferences. But be sure to avoid NullPointerException when referring to UserPreferences - it is not always available.

**Comment by ClaudiaPHI** [comment]
I looked into it and it seems more work that it actually worth it.

**Comment by kaspersorensen** [comment]
As far as I can see it _should_ already respect the datastore directory:

```
    @Override
    public void configureForFilterOutcome(AnalysisJobBuilder ajb, FilterDescriptor<?, ?> descriptor, String categoryName) {
        final String dsName = ajb.getDatastore().getName();
        final File saveDatastoreDirectory = userPreferences.getSaveDatastoreDirectory();
        final String displayName = descriptor.getDisplayName();
        file = new File(saveDatastoreDirectory, "output-" + dsName + "-" + displayName + "-" + categoryName + ".csv");
    }

    @Override
    public void configureForTransformedData(AnalysisJobBuilder ajb, TransformerDescriptor<?> descriptor) {
        final String dsName = ajb.getDatastore().getName();
        final File saveDatastoreDirectory = userPreferences.getSaveDatastoreDirectory();
        final String displayName = descriptor.getDisplayName();
        file = new File(saveDatastoreDirectory, "output-" + dsName + "-" + displayName + ".csv");
    }
```

**Comment by ClaudiaPHI** [comment]
I choose this directory as default
![Uploading image.png . . .]()

but the suggestion is in this folder: 
C:\Program Files\DataCleanerRC5\DataCleaner-staging.xlsx

**Comment by ClaudiaPHI** [comment]
The problem is for the Excel Files but I cannot find an easy way to do it. User Preferences is null at the moment we create the initial excel file. I suggest to close the issue, since it is not worth the time.

**Comment by kaspersorensen** [comment]
Let's not close it if the issue prevails... But we can move it out of the 4.0 milestone and stop caring about it for now.

**Comment by ClaudiaPHI** [comment]
ok.

**Comment by jhorcicka** [comment]
After a consultation with @ClaudiaPHI, we agreed to close this issue. It's not a real bug that files are not copied anywhere as long as the datastores contain the path.
