### ISSUE TITLE
Improve the buttons from the results window

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#288]
![image](https://cloud.githubusercontent.com/assets/6339923/6284433/2d214e9c-b8f0-11e4-88c4-376b606baa19.png)

The buttons for saving results need to be more visible and self explanatory. For example "Export summary metrics" button is not visible enough. "Save results" is not clear. 
Suggestions: 

- Add tooltip 
- Add information about what is mean for what use

**Comment by kaspersorensen** [comment]
Or suggestion from my side would be to consider only having one button which would toggle a popup of options. I think all the current options are related to some way of saving/exporting the results. So a "Save..." button with a popup of various options would suit the purpose fine I think.
