### ISSUE TITLE
UnitTest "JaxbJobReaderTest.testInvalidRead()" fails on non-english systems

### ISSUE THREAD

**Issue by michaelaerni** [datacleaner/DataCleaner#291]
When building/testing DataCleaner on a non-english system, the unit test JaxbJobReaderTest.testInvalidRead() in DataCleaner-xml-config fails. This prevents builds using "mvn clean install". The problem is the assertion:
```
assertTrue(message, message.startsWith("javax.xml.bind.UnmarshalException: unexpected element "
		+ "(uri:\"http://eobjects.org/analyzerbeans/job/1.0\", local:\"datacontext\")."));
```

If I run the test for example on a german system, the actual exception message starts with:
```
javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"http://eobjects.org/analyzerbeans/job/1.0", lokal:"datacontext"). Erwartete Elemente sind [...]
```

I tried to set the locale using -Duser.language=en, this however didn't work either. I then changed my system language to en-us and the test passed.

Could you adjust the test so it works in every language or at least put a remark into the contribution guide?

Tested:
Windows 8.1 Pro N, 64 Bit, en-us: Test passed
Fedora 21, 64 Bit, en-uk: Test passed
Windows 8.1 Pro N, 64 Bit, de-ch: Test failed

Output of DataCleaner/engine/xml-config/target/surefire-reports/org.datacleaner.job.JaxbJobReaderTest.txt:
```
-------------------------------------------------------------------------------
Test set: org.datacleaner.job.JaxbJobReaderTest
-------------------------------------------------------------------------------
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.047 sec <<< FAILURE! - in org.datacleaner.job.JaxbJobReaderTest
testInvalidRead(org.datacleaner.job.JaxbJobReaderTest)  Time elapsed: 0.031 sec  <<< FAILURE!
junit.framework.AssertionFailedError: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"http://eobjects.org/analyzerbeans/job/1.0", lokal:"datacontext"). Erwartete Elemente sind <{http://eobjects.org/analyzerbeans/job/1.0}columns>,<{http://eobjects.org/analyzerbeans/job/1.0}data-context>,<{http://eobjects.org/analyzerbeans/job/1.0}variables>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at org.datacleaner.job.JaxbJobReaderTest.testInvalidRead(JaxbJobReaderTest.java:222)
```

All other unit tests work fine on a non-english system.

**Comment by kaspersorensen** [comment]
Thank you for making us aware of this. Not fully sure how to prevent this. Seems it's a JAXB "feature" to translate the exception message... Will see if I can find a way to set the Locale. Maybe you can also help with research in this area?

**Comment by michaelaerni** [comment]
Thanks for fixing this
