### ISSUE TITLE
String pattern filter does not see an update of the pattern.

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#302]
1) Create a job with a String pattern filter.
2) Run the job.
3) Go to More -> String patterns and edit the pattern
4) Run the same job.

Expected output:
The results of the filter are going to be different as the string pattern has changed

Actual output:
The filter did not see that the pattern has changed and works on the old version - same results as during the first run.

5) Save and close the job.
6) Load the job again.
7) Run the job to see the updated results.

**Comment by ClaudiaPHI** [comment]
This issue is caused by a listener problem. The job is not updated until the next reload because it depends on the MultipleStringPatternPropertyWidget as listener. Therefore if the dialog configuration of the String Pattern filter is not open, the change won't be registered.

**Comment by ClaudiaPHI** [comment]
The same issue occurs for Simple Dictionary
