### ISSUE TITLE
New datastore management page does some strange wrapping

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#304]
There seems to be some kind of bug in the layout for the datastore management: 
![image](https://cloud.githubusercontent.com/assets/1282832/6373831/7cbbe4a0-bd0d-11e4-8e09-8838ccefac7e.png)

Both files has semi-long paths, that would easily clash with the buttons. I guess that could be the trigger.

**Comment by kaspersorensen** [comment]
Duplicate issue - see 263
