### ISSUE TITLE
Alternative execution button options

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#324]
We currently just have a single execution button, but sometimes we get requests like:

 * Could we run the job just on a sample of the data (kinda like a quick preview)
 * How to trigger the job to run clustered
 * How to trigger the job to run remotely
 * How to run the job with a custom amount of threads (for benchmarking etc).

We'd still want the simple execute button as default, but offer more options in a drop-down button a la this mash-up:

![image](https://cloud.githubusercontent.com/assets/291450/6634906/9422c0b0-c95f-11e4-8fcc-fe07a8d7e73a.png)

**Comment by LosD** [comment]
What should happen when they've run in a special mode once? Shouldn't it stick?

Maybe not for the "preview mode", but I would imagine that if you want to run it on a cluster or remotely, you would like to do that every time.

**Comment by kaspersorensen** [comment]
We could consider saving that as a user preference I guess. But to begin with I would be more than happy even with the "just once" option.
