### ISSUE TITLE
Automatic component reference documentation generation

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#343]
An automatic "Component API documentation" tool for DataCleaner. Either fully integrated into the desktop app or as a tool which can generate HTML documentation (a la javadoc). Or both even.

I imagine that in the tree of the desktop app one could click e.g. the Pattern Finder and then be brought to a screen/page that contains documentation of this component. The documentation could contain many elements, all generated based on the ComponentDescriptor and related classes:

 * Name
 * Type of component (transformer, filter, analyzer)
 * Description
 * Icon
 * Execution details:
  * Is it concurrent?
  * Can it be distributed?
 * Each property can be listed, including details like:
  * Name
  * Type of property (InputColumn, String, Number, Enum etc.)
  * Description
  * Any constraints set by e.g. StringProperty, NumberProperty etc. annotations.
  * Is it mapped to any other property (via MappedProperty annotation)
 * If the component has a result, what is the result type
  * And if the result type exposes any metrics, describe each metric name and type.

**Comment by ClaudiaPHI** [comment]
![image](https://cloud.githubusercontent.com/assets/6339923/7135371/61275044-e2a6-11e4-8333-6fe4cc9a8e47.png)

**Comment by ClaudiaPHI** [comment]
![image](https://cloud.githubusercontent.com/assets/6339923/7271961/756ce248-e8e7-11e4-831b-878c47aa0a42.png)
