### ISSUE TITLE
 add .csv extension when writing to a CSV file

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#346]
Consider automatically adding the csv extension or make the user add  the extension to the file name.

**Comment by kaspersorensen** [comment]
Hmm this seems a bit strict... At the very least I would like to include other common extensions to CSV formatted files as well:

 * txt
 * tsv

You can get this info from the FileFilters class which is already the defacto standard in DC for file extension management.

**Comment by ClaudiaPHI** [comment]
ok. I will do it.
