### ISSUE TITLE
Monitor metrics from analyzers with multiple result types

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#347]
In DataCleaner enterprise edition we have an analyzer type (Duplicate Detection) which may produce different result types, so basically it implements Analyzer<AnalyzerResult> and the concrete result type is determined at runtime.

In DC monitor that currently means we get an empty metric list when building timelines, because the code is looking only at the component descriptor:

![image](https://cloud.githubusercontent.com/assets/291450/6779647/7e6d693a-d15e-11e4-9532-1bb72d766254.png)

To improve this we should also take into account the concrete historic results. Check if the job has run previously and if so, take the latest result and build the metric selection based on that.

(Addition by @LosD): The actual problem has changed a bit. See discussion for full details.

**Comment by jhorcicka** [comment]
Not valid anymore.

**Comment by LosD** [comment]
Not sure I understand, how is it not valid anymore?

**Comment by jhorcicka** [comment]
Maybe I misunderstood the problem, but according to the description there should be an empty "metric list" when trying to create a timeline for a job containing "Duplicate detection" component. I've just tried that and it was not empty. There was one value to select.

**Comment by LosD** [comment]
Okay... I don't think we changed anything here, so that's pretty weird. @kaspersorensen can you confirm that it is now working as intented?

**Comment by kaspersorensen** [comment]
I don't have any means of verifying that :) Except for building everything from scracth of course but I expect that I will miss access to certain HI artifacts via VPN and such, which I can't access anymore.

**Comment by kaspersorensen** [comment]
But verifying it for yourself should also be possible (and faster than asking me to do it): Simply run the default DC monitor and then go to the dashboard -> customer duplicates and then click the edit button for the timeline.

**Comment by LosD** [comment]
Hmmmm... Yeah, that is certainly simple, as well as completely missing from the original description :)

**Comment by LosD** [comment]
Still not sure about details at all, though. Will this nuke output from all analyzers in the job, or only the dedup output itself?

**Comment by LosD** [comment]
The output certainly seems to be there:
![image](https://cloud.githubusercontent.com/assets/1282832/18427309/910a85e8-78c7-11e6-87d2-f30b6443242d.png)

Just surprises me that it is fixed "by accident" when it seems to require specific steps to fix.

**Comment by kaspersorensen** [comment]
It seems to have been "almost" fixed. But I notice that none of the checkboxes are checked in that screenshot. That would mean no metrics are being plotted, but I think the old metrics are being plotted, right? Essentially I guess the "metric matching" should somehow revert to see if there are metrics that match on name, arguments etc. even though the result type/class has changed due to a software upgrade.

**Comment by LosD** [comment]
Yep, plotting of results are fine:
![image](https://cloud.githubusercontent.com/assets/1282832/18464658/a84eb3ca-7992-11e6-82ff-ab60ea45cb55.png)

Let's reopen. I'll add a sentence to the description

**Comment by stefanjanssen** [comment]
I don't think this is solved either. In Duplicate Detection there is currently a (somewhat ugly) work-around which involves creating an abstract class containing all metrics from all possible result types that can be returned from the analyzer. With the work-around in place it works, but not sure if it does otherwise. Unless we decide to live with the work-around forever, which I would prefer to avoid.

**Comment by kaspersorensen** [comment]
No longer relevant since DC monitor is not in community edition.
