### ISSUE TITLE
Do not call AnalysisListener.jobSuccess() before any AnalyzerResultFutures have finished

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#353]
Right now we notify listeners of the jobSuccess() event when the last analyzer has delivered a result object. But since 4.0 we have the AnalyzerResultFuture object which indicate a "not yet finished result" object. These are listenable and this mechanism should be respected by the AnalysisListener to not prematurely indicate a fully finished job.

**Comment by ClaudiaPHI** [comment]
Can you explain a little bit more ?

**Comment by kaspersorensen** [comment]
AnalysisListener is a general interface that can be used for many purposes to listen for different events that happen in the execution of a job. One of it's methods is jobSuccess(...) which is invoked when a job finishes.

Currently the invocation of jobSuccess(...) happens the moment all AnalyzerResults have been collected. But since we introduced AnalyzerResultFuture there might now still be a delayed processing taking place still. So if one or more of the AnalyzerResults are instances of AnalyzerResultFuture.we need to delay the invocation of jobSuccess(...) till the time when all the futures are also finished.

A working approach to this is to use the AnalyzerResultFuture.addListener(...) on all the futures and register a "count down" there that will eventually make the AnalysisListener.jobSuccess(...) call delayed as well. Pseudo code:

```
AnalysisListener listener = ...
AnalysisResult result = ...
List<AnalyzerResultFuture> futures = result.getResultsOfType(AnalyzerResultFuture.class);
if (futures.isEmpty()) {
  listener.jobSuccess(...);
} else {
  CountDownLatch latch = new CountDownLatch(futures.size());
  for (future : futures) {
    future.addListener(new Listener() {
      void onSuccess() {
         latch.countDown();
      }
    }
  }
  latch.await();
  listener.jobSuccess(...);
}
```
