### ISSUE TITLE
The Oracle datastore does not allow to specify connections with service name or easy connect string 

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#355]
# Actual
The Oracle datastore type tab "Oracle connection" provides parameter fields for 'Hostname", "Port", "System ID (SID)", "Username" and "Password".

Oracle versions can also connect using the service name. However, the Oracle data store only works when you specify the SID.

Oracle also has the "easy connect string", which is also not supported.

#Expected
The Oracle datastore should allow connections by specifying the service name and also by specifying the easy connect string.

Oracle documentation on the easy connect string:
http://www.oracle.com/technetwork/database/enterprise-edition/oraclenetservices-neteasyconnect-133058.pdf

**Comment by kaspersorensen** [comment]
Pull request available here: #369
Please review
