### ISSUE TITLE
Dragging CSV file onto drop zone leads to NullPointerException

### ISSUE THREAD

**Issue by manuelvandenberg** [datacleaner/DataCleaner#356]
When I drag any of two attached CSV files on the DropZone in DC4  pro edition, I'll get a NullPointerException.

This happens if the CSV is not yet known as a datastore in DataCleaner. Once it is added, it work OK.

The CSV files seem to be nothing special, but find them attached anyway.

**Comment by manuelvandenberg** [comment]
Uhoh. Cannot attach files. Thats a BIG bummer. They are here:
https://drive.google.com/a/humaninference.com/folderview?id=0B-yy3IlR-ORhMkxESDlwcGV6ZUk&usp=sharing

**Comment by tomaszguzialek** [comment]
The files appeared to have the extension in capital letter, e.g. CSV instead of csv. When lowercased, it works correctly, so this would be a quick workaround. Of course, we should be resilient to such case, so I will prepare a fix for it.
