### ISSUE TITLE
Document how to connect to DB2 and other commercial databases

### ISSUE THREAD

**Issue by manuelvandenberg** [datacleaner/DataCleaner#358]
Users are struggling with connecting to DB2.
It would help if we describe the required steps in the documentation:
- How to add the driver to you classpath
- How to add the drivers as a datastore in Datacleaner
- How to test if your setup is correct
- How to connect to the actual database

This popped up for DB2 but may hold for other databases where we do not ship the driver itself.

**Comment by kaspersorensen** [comment]
For reference: http://datacleaner.org/resources/docs/4.0.1/html/ch14s01.html
