### ISSUE TITLE
Sorting in Create CSV and Create Excel works incorrectly for numeric content

### ISSUE THREAD

**Issue by Jan-Arie** [datacleaner/DataCleaner#360]
In  Create CSV file and Create Excel File it is possible to select a 'Column to be sorted on'  under 'Optional properties'. 
It sorts, but not correctly for numeric input, such as ID's. Numbers are being sorted alphabetically?
ID's had been created by use of DC transformer <Generate ID>.
I even applied transformer Convert to number, but still the same incorrect ordering in output.

Ordering of output is important for tracability / readibility of results,since DC transformers randomize order due to multi-threading.

**Comment by Jan-Arie** [comment]
![result_write_to_csv_and_sort_in_id](https://cloud.githubusercontent.com/assets/10989888/6939067/f361f024-d868-11e4-84ec-96a188e4e1fb.png)
![result_write_to_excel_and_sort_on_id](https://cloud.githubusercontent.com/assets/10989888/6939069/f36372c8-d868-11e4-8552-dfce54058cec.png)
![write_to_csv_and_sort_on_id](https://cloud.githubusercontent.com/assets/10989888/6939068/f3620244-d868-11e4-96ae-de6abc444fd4.png)
![write_to_excel_and_sort_on_id](https://cloud.githubusercontent.com/assets/10989888/6939070/f3656790-d868-11e4-80c2-3ae687d7917e.png)

**Comment by ClaudiaPHI** [comment]
Can I have the file Jan-Arie ?

**Comment by ClaudiaPHI** [comment]
It is a sorting issue. I will try to solve it

**Comment by tomaszguzialek** [comment]
Work on feature/360-sort-integers-numerically:
- [ ] Unit test reproducing the issue in CSV files
- [ ] Unit test reproducing the issue in Excel files
- [ ] Fix for numerical sorting in CSV files
- [ ] Fix for numerical sorting in Excel files

**Comment by tomaszguzialek** [comment]
Just realised that alphabetical sorting is still case-sensitive:
![case-sensitive sorting](https://cloud.githubusercontent.com/assets/1483194/7606688/6749e1c8-f95b-11e4-9b18-8817d9666d03.png)

**Comment by tomaszguzialek** [comment]
Another issue arised: the comparator uses the type from getDataType() method. While reading a CSV or an Excel file, this type is reset to String fooling the comparator.

**Comment by tomaszguzialek** [comment]
Created a pull request (#431) for solving case-sensitivity and a separate issue for the CSV and Excel always reporting String type (#432).

**Comment by tomaszguzialek** [comment]
When using CSV or Excel files as a source in the job, use ConvertToNumberTransformer on a column that sorting should be performed on - this does the trick now.
