### ISSUE TITLE
Create a -version option

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#362]
It would be good to add a command line option to DataCleaner that prints the version information and then exits, like the "mvn -version" command.

**Comment by kaspersorensen** [comment]
Note from my side: Would be nice if the version checker would check both the DataCleaner core version and also it's packaging version (community or commercial editions have packaging projects where the version might be slightly skewed if there are e.g. multiple DC EE releases on top of the same core DC version).

**Comment by drexler42** [comment]
Yes. I will include that.
