### ISSUE TITLE
Deduplication model example job is outdated

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#378]
The example file is "Customers.csv"

**Comment by kaspersorensen** [comment]
I cannot find this anywhere ... Looked through all the files in ```desktop/ui/src/main/resources/datacleaner-home/jobs``` and no reference to Customers.csv.

Maybe it's just your local copy of the job that is faulty?

**Comment by tomaszguzialek** [comment]
I have DC 4.0 installed and I nuked my home folder just now to make sure it is recreated. When loading ~/.datacleaner/4.0/jobs/dedup_customers.dedupmodel.xml into Duplicate Detection, there is a red icon.

**Comment by kaspersorensen** [comment]
Aha, well that's not a bug but a feature :-) The model file fits the set of transformations done in the job where it is configured - dedup_customers_detection.analysis.xml - it looks like this:

![image](https://cloud.githubusercontent.com/assets/291450/7253147/b4a142c2-e83a-11e4-9bec-b945f5cb0b19.png)
