### ISSUE TITLE
Example job 'cleansing street'

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#387]
Following the implementation of #159, we should have an example data cleansing job that does various correction tasks to our example data, filters the validated from the invalid parts and does some common reject writing to a file. In a diagram something a la this:

```
Src -> Corr1 -> F1 -> Corr2 -> F2 -> Write success
                 \             /
                   \        /
                 Write rejects
```

**Comment by ClaudiaPHI** [comment]
What do you think about this sample job ? 

![screen shot 2015-10-15 at 11 16 47 am](https://cloud.githubusercontent.com/assets/6339923/10509631/8fc0b6d4-732e-11e5-968b-98bf4d55f3e7.png)


It's a nice example. We have customers over 100 years old :-D 

![screen shot 2015-10-15 at 11 20 44 am](https://cloud.githubusercontent.com/assets/6339923/10509737/12dc95a6-732f-11e5-825a-3eae915aa0b2.png)

**Comment by ClaudiaPHI** [comment]
What about this @kaspersorensen ? 
![screen shot 2015-10-15 at 11 49 38 am](https://cloud.githubusercontent.com/assets/6339923/10510553/0800530c-7334-11e5-94a1-7a3ccc5ac4ee.png)


Can't we add both of the example jobs ?

**Comment by kaspersorensen** [comment]
Looks good. I am always in favor of having more examples, so I am fine with adding both.

Be aware when you commit of a few things:

Don't reveal any EasyDQ credentials in the job. I believe we have a special value (in .analysis.xml) called "demo" for the Connection property.

I would give the components some names to make the jobs easy to read. For instance use the component names to show that here are customers above 100 years and so on.
