### ISSUE TITLE
Possibility to surpress the "Save Result" buttons / Minimal analyzer result screen

### ISSUE THREAD

**Issue by stefanjanssen** [datacleaner/DataCleaner#430]
Currently DataCleaner always shows several button above analyzer results. While these make sense for most analyzers, for some it does not. Examples are ID7 training tool, but also write to file like analyzers. If there would be a possibility to hide these buttons, it would result in a cleaner, less confusing UI for users.

Ideally, the buttons would not only be hidden, but the datacleaner banner in general would be minimized, to allow maximum screen space for the analyzer result itself.

**Comment by stefanjanssen** [comment]
So I made a quick paint edit of how this more minimal screen could look:

![modified_result_screen](https://cloud.githubusercontent.com/assets/6106276/7682213/c54f97c6-fd76-11e4-90f2-06a585326e09.png)

**Comment by kaspersorensen** [comment]
Oh I think this actually is fixed, it just never got closed!
