### ISSUE TITLE
More Complicated ElasticSearch Mappings Are Not Processed Correctly

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#438]
If an index mapping contains more than the basic hierarchy, datacleaner does not process the mapping schema correctly.

For instance, a field with the mapping

{"myfield":{"index":"not_analyzed","type":"string"}}

would be processed into two different fields "myfield" and "index."

If a mapping contains more than one object at the same level as the properties object, none of the fields in the properties object are processed correctly.  For instance, if a dynamic_template is present or if date_detection is turned off, the fields won't be processed correctly.  The mapping below is processed by DataCleaner into the fields in the image.

{
  "mappings": {
    "metric_data": {
      "date_detection": "false",
      "dynamic_templates": [
        {
          "non_data_strings": {
            "match": "*",
            "unmatch": "data.* ",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": "true"
            }
          }
        }
      ],
      "properties": {
        "data.AssetName": {
          "type": "string",
          "index": "not_analyzed",
          "doc_values": "true"
        }
      }
    }
  }
}
![dc_ex](https://cloud.githubusercontent.com/assets/3769059/7618014/cd145c54-f974-11e4-8b8a-f75008108150.png)

**Comment by maphysics** [comment]
A quick look at the code, it seems that in ElasticSearchDataContext.java in MetaModel-elasticsearch, in detectTable there is an iterator that doesn't actually iterate through the entries in the map.  If a check is added to make sure that only the properties item is parsed that would likely fix the second issue and allow the user to remove the extra fields.  

The first case is solved in ElasticSearchMetaDatParser.java by on line 40 splitting on '}, ' rather than on a comma.  It then leaves the individual settings for each field grouped together and associated with the field instead of splitting them into their own fields.

I'll make these changes on a local branch of MetaModel-elasticsearch and submit a pull request over on that repo.  See if I can't get the changes accepted.

**Comment by kaspersorensen** [comment]
Thank you for the bug report and the good work to find the culprit! Will help you through the MetaModel acceptance since we also play in that community :-)

**Comment by maphysics** [comment]
Cool.   I also noticed that these changes will also affect how the types get picked up and I'm working on some logic for that too.

**Comment by maphysics** [comment]
So I have the changes on a fork and I have submitted a bug to the jira project.  When I go to create the pull request as par the instructions in the repo, I don't see the edit and create pull request buttons after I compare with my forks hash.  Is there a step I'm missing to give me permission to create the pull request?

**Comment by maphysics** [comment]
So I have a pull request open for this [1] and the CI test is failing.  It's not reproducible for me locally.   What should I expect the process to be from here?

[1] https://github.com/apache/metamodel/pull/23

**Comment by kaspersorensen** [comment]
Let's track the resolution of that issue where it is most relevant, on your PR's review remarks / comments.

**Comment by kaspersorensen** [comment]
I guess we can close this one too then. Will be available in next release (or latest build) of DC!
