### ISSUE TITLE
Add all tabs to result window as soon as possible

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#443]
Good suggestion by @LosD: Instead of adding tabs to the result window while the job is running, it would make the experience less "jumpy" if we already from the start produce the tabs that should be available when the job is finished.

An addition from my side: Would be neat if they are initially then disabled/grayed and then as the results become ready we will make them enabled.

This feature would also make sorting of the result tabs more consistent and deterministic - so it fixes #286

**Comment by ClaudiaPHI** [comment]
:+1:
