### ISSUE TITLE
Dynamic analyzer name in the analyzer result screen

### ISSUE THREAD

**Issue by stefanjanssen** [datacleaner/DataCleaner#468]
As far as I am aware, the name displayed in the analyzer result screen is created from the analyzer name. For clarity, this is what I'm talking about:
![analyzer result name](https://cloud.githubusercontent.com/assets/6106276/7940383/cbc41a92-0950-11e5-9293-375606649597.png)

This fixed behaviour is problematic in analyzers for which the name depends on some settings. For example, the Identify7 analyzer has multiple modes. Even if selecting 'training' mode, the analyzer result still gets listed as 'duplicate detection'. As this is the name of another mode, the overall result is confusion.

**Comment by kaspersorensen** [comment]
Another aspect that is also important here is that the user should be able to link the name he sees here with the name of the node in the graph on the "canvas" screen. Actually we do have an interface that components can optionally implement to provide suggested names on the canvas - it is called HasLabelAdvice.

So my suggestion is to change the result screen to also take into account HasLabelAdvice. That way you can change the particular analyzer to give a label advice based on the "mode" property and this label should then also be applied on the result screen.

Note on wording: It is not that the analyzer name itself is changing - it is the analyzer _instance_s identifying name that is changing. But that's just nitpicking :)
