### ISSUE TITLE
Run analysis job using the return of HTTP Request

### ISSUE THREAD

**Issue by phelipemaia** [datacleaner/DataCleaner#488]
Is it possible to run an analyzer using the return of an URL? I have a REST service that retrieve a JSON object and I want to analyze this object.
I was wondering if I need to create a new connector or if does exist an easier way to do that.

**Comment by drexler42** [comment]
Hi. I don't think DC has a component that does this. But I suppose you can always use a JavaScript transformer to invoke the REST service and write the results to the output of that transformer. That way, you can do almost anything.

cheers,

Hans

**Comment by phelipemaia** [comment]
Hi @drexler42 

I think it's a little more complicated. What I was trying to do is probably create a new Connector. This connector will be a RESTConnector (like Oracle, SugarCRM, SalesForce, etc) and I would run the analysis using the data retrieved by this REST request. 
So, I would create a config with username, password (basic auth), URL, and with these configs I would ran the analysis. Do you know what I mean?

cheers

**Comment by phelipemaia** [comment]
For those who wanna know about this discussion: http://datacleaner.org/topic/1081
