### ISSUE TITLE
Roll HttpComponent version forward

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#491]
The httpcomponents.version number appears to collide with the correct version of apache http core when using apache http fluent to make rest calls.  It is an old enough version to collide with newer packages relying on apache http components.  Currently it's 4.2.5 many of the apache http packages are up to 4.4+ now.

**Comment by maphysics** [comment]
The only test that failed to build after changing the version to 4.4.1 was UserPreferencesImplTest.java testCreateHttpClientWithNtCredentials() at line 115, the slash is facing the wrong direction.  

        authScope = new AuthScope("host", 1234, AuthScope.ANY_REALM, "ntlm");
        credentials = httpClient.getCredentialsProvider().getCredentials(authScope);
        assertEquals("[principal: FOO/bar][workstation: " + computername.toUpperCase() + "]", credentials.toString());

**Comment by kaspersorensen** [comment]
Maybe we can just adapt the assertion then. Maybe something as crude as using

credentials.toString().replace('\\','/')

**Comment by maphysics** [comment]
Sounds good except the first of the slashes needs to be escaped

**Comment by kaspersorensen** [comment]
Maybe finds your interest to review this pull request which upgrades HTTP components: #524
