### ISSUE TITLE
Hard to remove extension in DataCleaner commercial editions

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#503]
After adding an extension manually in the DataCleaner commercial editions (4.0.8), it is impossible to remove them. There is no remove button in the Options-extensions dialog. When the extension jar is no longer present, the extension will show in RED, but it is impossible to remove it...

![2015-07-14 16_00_28-new issue datacleaner_datacleaner](https://cloud.githubusercontent.com/assets/5919509/8674964/860ece40-2a41-11e5-86f4-f4b91327a27d.png)

The screenshot shows the problem. 
- I manually removed the NameUniversal transfomer jars. They now show in red.
- There is no way to remove the EirCode transformer.

**Comment by kaspersorensen** [comment]
I have a strange feeling that this may be something as silly as a scrollbar issue. I think the remove buttons are out of the view on the right side of the panel.

Still a bug of course ;-)

**Comment by drexler42** [comment]
Ah yes, you are right. The remove button appears when I widen the window. Well, at least there is a work-around then!

**Comment by kaspersorensen** [comment]
No longer applicable to CE
