### ISSUE TITLE
A better widget for entering Salesforce.com endpoint URL

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#517]
Today we have just a plain text field for entering SFDC's endpoint URL:
![image](https://cloud.githubusercontent.com/assets/291450/8795401/15e9f620-2f8d-11e5-8f8b-5be7f80652e9.png)

While in 99% cases the URL would either be blank (default) or the test/sandbox URL: https://test.salesforce.com/services/Soap/u/28.0

So let's instead make an (editable) combobox with those two choices and then also the option to enter a custom URL.

**Comment by LosD** [comment]
We decided to take out the edtitablility, since the JComboBox is a little annoying. For now, we'll just add an externally edited URL to the list.
