### ISSUE TITLE
Get rid of derby.log file from DC application directory

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#528]
Since we've introduced the Apache Hive support I am now noticing an unfortunate side-effect: Every time I run DataCleaner I see that a file called "derby.log" is located in my application directory. The file is empty, yet is an annoyance and I am not sure if it could even be a problem on installations where the user does not have write-access to the application directory.

I did a bit of research and it seems that Apache Hive uses Derby for the so-called "metastore", a metadata database. We should see what we can do to avoid this log file in DC just because of that.

**Comment by kaspersorensen** [comment]
Maybe an approach will be to set this system property ```derby.stream.error.file``` to point to a temp dir  (or DATACLEANER_HOME) or so. But I wouldn't know where to do that - the main class? And what about DC monitor then.

**Comment by LosD** [comment]
There is also an alternative, according to this posting: http://stackoverflow.com/questions/1004327/getting-rid-of-derby-log#1004686

Make a OutputStream subclass that writes to nothing (or maybe to a proper Logger), and point ```derby.stream.error.field``` to a constant of that.

It still doesn't change the issue with us having to set the variable, but at least we don't need to find a place to dump the file.

**Comment by LosD** [comment]
It _is_ also possible to put a derby.properties file in the DataCleaner program folder (actually in the derby home directory, but I assume that to be the DataCleaner folder when started by DataCleaner) with that property set.

**Comment by kaspersorensen** [comment]
I prefer not having a Derby config file, but using the dev null stream thing is also fine by me.
