### ISSUE TITLE
Add OutputDataStream suppport to analyzer

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#551]
Currently, there is no analyzer actually publishing OutputDataStream(s), so doing real-world tests of #516 and (especially) #519 is a bit problematic.

Identify a good candidate and implement HasOutDatastream on it.

**Comment by kaspersorensen** [comment]
Fixed by #549 which is still debated tho'.

**Comment by LosD** [comment]
Wouldn't that be #553 (although it seems I accidentally wrote that #553 would fix #549, when it should have said it fixed this one)?

Anyway, effect of #553 is being removed as part of the fix for #554, instead using the CompletenessAnalyzer as suggested (which, as a bonus is also simpler since the rows can be added to the OutputRowCollectors directly during the run, instead of having to wait for the result. And it demonstrates multiple streams).
