### ISSUE TITLE
JS job fails on monitor server

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#552]
Reporting this bug to investigate on behalf of another user. When deploying an advanced JS transformer job on DC monitor, this issue occurs:

```
11:06:05 - Job execution FAILURE
- Can't find method ch.qos.logback.classic.Logger.debug(string,java.lang.String[],java.lang.Object[],org.eobjects.analyzer.job.concurrent.ThreadLocalOutputRowCollector). (JavaScriptAdvancedTransformer#8) (EvaluatorException)
- Failure component: ImmutableTransformerJob[name=Q_Invalid_Columns,transformer=JavaScript transformer (advanced)]
```

**Comment by kaspersorensen** [comment]
Looks like we maybe have a wrong import. The logback import should probably just be a slf4j import

**Comment by LosD** [comment]
Nope, unless it was changed recently, it doesn't seem like any Java code is using Logback directly:
https://github.com/datacleaner/DataCleaner/search?q=logback&type=Code

... Which makes the error pretty weird. Will a quick reproduce tomorrow.

**Comment by kaspersorensen** [comment]
Hmm ok it could be we're chasing a ghost then. Maybe the syntax of the script (which I don't have) is simply wrong. Saying this because the JS transformer allows you to access the logger object directly.

**Comment by LosD** [comment]
Does it work when he's using it in desktop DC? That would probably rule out the script unless it is really complicated code that can be affected by how it is run.

**Comment by LosD** [comment]
Reproducing in the monitor will have to wait a bit. I can't even register a datastore... I get a "Caused by: java.lang.NoClassDefFoundError: Could not initialize class freemarker.template.Configuration" as soon as I choose CSV and press next. Not really sure if it is my setup or a general problem.

**Comment by kaspersorensen** [comment]
Seems it only happens on the monitor. From the user's email:

"... thanks for the response, correct the code works fine on my desktop but not on the server. However, after commenting the "logger.debug..." it worked on the server."

**Comment by kaspersorensen** [comment]
He also shows his code. Here's the important part:

```
var transformerObj = {
        initialize: function() {
                logger.info('Initializing advanced JavaScript transformer...');
        },

        transform: function(columns,values,outputCollector) {
                logger.debug('transform({},{},{}) invoked', columns, values, outputCollector);
                ...
        }
```
What I think is going wrong here is maybe that the varargs debug(..) method of SLF4j is not bound properly to the javascript call. It could be a limitation of rhino or so. It could also have to do with the fact that there are many methods called debug (it's overloaded a lot).

**Comment by LosD** [comment]
That looks very much like the standard example, so he is doing nothing funky  :)

If Rhino was the culprit, wouldn't desktop and server suffer equally?

**Comment by kaspersorensen** [comment]
Good point. Yeah I don't know then.

No sweat wrt reproducing. For now he just stopped logging it.

**Comment by jhorcicka** [comment]
Problem with ```logger.debug('transform({},{},{}) invoked', columns, values, outputCollector)``` is org.datacleaner.job.concurrent.ThreadLocalOutputRowCollector outputCollector. Without that it works fine.
