### ISSUE TITLE
(Some) listeners should be added to OutputStream AnalysisJobBuilders

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#594]
We have some issues regarding updating the graph on changes in output streams, as the listeners from the root analysis job builder does not propagate to the output stream job builders. We do not want all listeners to just be copied, but somehow that the listeners are given a choice, maybe using some kind of "outputstream added" event that they could react to.

**Comment by kaspersorensen** [comment]
I'm pretty sure that this is the cause of #580
