### ISSUE TITLE
master parent fails to build due to banned dependencies

### ISSUE THREAD

**Issue by maphysics** [datacleaner/DataCleaner#615]
Datacleaner-spark banned dependencies cause datacleaner parent to fail to build on master.  The packages appear to be dependencies of other modules.  Commenting out the exclusions in the datacleaner-spark pom allow the parent pom to compile.  The install passes without the exclusions.

[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-versions) @ DataCleaner-spark ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: org.apache.curator:curator-client:jar:2.6.0
Found Banned Dependency: org.apache.hadoop:hadoop-yarn-common:jar:2.7.1
Found Banned Dependency: org.apache.hadoop:hadoop-yarn-api:jar:2.2.0
Found Banned Dependency: org.apache.hadoop:hadoop-common:jar:2.7.1
Found Banned Dependency: org.apache.hadoop:hadoop-auth:jar:2.7.1
Found Banned Dependency: org.apache.hadoop:hadoop-annotations:jar:2.7.1
Found Banned Dependency: org.scala-lang.modules:scala-xml_2.11:jar:1.0.2
Found Banned Dependency: com.fasterxml.jackson.core:jackson-annotations:jar:2.4.6
Found Banned Dependency: org.apache.curator:curator-recipes:jar:2.6.0
Found Banned Dependency: org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.1
Found Banned Dependency: com.fasterxml.jackson.core:jackson-databind:jar:2.4.6
Found Banned Dependency: org.scala-lang:scala-library:jar:2.11.4
Found Banned Dependency: org.apache.curator:curator-framework:jar:2.6.0
Found Banned Dependency: com.fasterxml.jackson.core:jackson-core:jar:2.4.6
Use 'mvn dependency:tree' to locate the source of the banned dependencies.

**Comment by kaspersorensen** [comment]
Weird, I heard this also today from another developer. Yet it doesn't happen on my machine or anyone in my team's machines. And also Travis CI is fine.

What version of Maven are u using?

**Comment by maphysics** [comment]
I'm using mvn 3.2.3 on windows.  I'm building through intellij.

**Comment by kaspersorensen** [comment]
I'm guessing this has something to do with the fact that those dependencies are available at "provided" scope but banned in "compile" scope. Logically I think that is fine, and it's how it is intended to be. But somehow it fails on some machines and I cannot figure out why. @ankit2711 also reported it to me and he thinks it's on Linux machines it fails only. Is your machine also a Linux machine @maphysics ?

**Comment by maphysics** [comment]
@kaspersorensen my machine is a windows machine running Windows 7 Pro

**Comment by kaspersorensen** [comment]
I just heard from @ankit2711 that upgrading Maven worked for him. Could you try to get a newer Maven version @maphysics ? I know it's kinda strange to ask because I have a lower version, but it could be a specific range of Maven versions that has some glitch here.

**Comment by maphysics** [comment]
I upgraded maven to 3.3.3.  Master installed fine with everything commented to populated the new m2 directory.  It also installed fine without everything commented and the m2 directory populated.

**Comment by kaspersorensen** [comment]
OK. Strange thing, seems some Maven versions aren't doing it right then. But I'll close the story now that we know how to fix it.
