### ISSUE TITLE
Sometimes AnalyzerResultFutureTest.testMultiThreadedListenerScenario is failing

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#621]
In line 150 we expect ```[43, 43, 43, 43, 43]``` but sometimes we get only 4 out of 5 elements (```[43, 43, 43, 43]```). This happens _very_ rarely, but is something we should get under control.

**Comment by LosD** [comment]
Ran the test ~1500 times in total (by using JUnit4 and `@RunWith(Parameterized.class)`), a bit from IDE and a bit from Maven, and I didn't see it happen. Of course, timing can be wildly different between machines and depending on what the machine can is doing (though I tried to stress my computer a bit using CPU burner), so there is really no way to be absolutely sure.

I also don't think we've seen it in any Travis builds recently (do anyone know of a good way to search Travis build errors?).

I will close this, then we can reopen it if we see it again.
