### ISSUE TITLE
Product Clean up

### ISSUE THREAD

**Issue by saikovvuri** [datacleaner/DataCleaner#625]
Hello, 

Does datacleaner support cleaning on raw text and standardization. We are looking at solutions to clean product data coming as raw text descriptions. 

Thanks

**Comment by kaspersorensen** [comment]
we have various capabilities in DC that might do that - depending on what you are specifically looking for. Take a look at stuff like the Reference data matcher, Regex parser, Synonym replace, Remove dictionary matches etc.
