### ISSUE TITLE
Improve file dropzone to allow selection of HDFS files

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#646]
Add a button next to the "(or click to browse)" button inside the dropzone to allow selecting/entering a HDFS resource path.

 - [x] The button should feature a small Hadoop (elefant) icon.
 - [x] Label should be "Select Hadoop HDFS file".
 - [x] The existing button should be relabeled to "Click to browse".
 - [x] When clicking the button we want to show the HDFS resource selector widget. Preferably inside the dropzone somehow - maybe replacing the position of the buttons.
 - [x] Once selected the automagic creation of datastore should function like/similar to selecting a normal local file.

**Comment by ClaudiaPHI** [comment]
For selecting a file we have a file chooser. 
Could it be an independent dialog that selects a HDFS Resource similar with a CSV Datastore dialog box ?

**Comment by ClaudiaPHI** [comment]
I have understood. Scratch the previous commentary.

**Comment by kaspersorensen** [comment]
Reopening to make a few adjustments, see PR comments #699
