### ISSUE TITLE
Drill-down option in ValueDistributionResult with grouping is "random"

### ISSUE THREAD

**Issue by tomaszguzialek** [datacleaner/DataCleaner#663]
When ValueDistribution is run together with grouping on some column, the result shows/doesn't show the drill-down arrow when necessary. 

1) In the screenshot, value "Project Manager" should have the drill-down option like the others.
2) In the screenshot, value "President" shows the drill-down arrow despite having count equal to 1.

![value-dist-drilldown](https://cloud.githubusercontent.com/assets/1483194/9850555/a3e2f77e-5af3-11e5-9778-de32804ce618.png)

**Comment by kaspersorensen** [comment]
This is by intention. To keep memory low we have a threshold on how many record sample sets we keep.
