### ISSUE TITLE
Graph UI lines of the OutputStream disappear 

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#667]
First Step: 
![image](https://cloud.githubusercontent.com/assets/6339923/9875484/a52c360c-5bae-11e5-93b1-06c0f368e47a.png)

Second step: 
![image](https://cloud.githubusercontent.com/assets/6339923/9875488/abc76658-5bae-11e5-9487-c97cb99ffc43.png)

Steps to reproduce: 

1. Build new job.
2. Choose _Customers_ datastore.
3. Add _Completeness analyzer_.
4. Link _customers.csv_ to _Completeness analyzer_.
5. Add _Create Excel spreadsheet_.
6. Link "Complete rows" to _Create Excel spreadsheet_
7. Set sheet name to "test" in dialog (Why is this needed? Shouldn't there be a default?)
8. Add _String analyzer_.
9. Link "incomplete rows" to _String analyzer_
10. Add _Convert to number_.
11. Double click _Convert to number_ and choose all rows.
12. Close

Expected behavior: Everything mapped correctly.

Actual behavior: One or more components may lose their mapping. I've seen zero loss, both lost their mapping and only _Create Excel spreadsheet_ lose it's mapping. At no point did I see _String analyzer_ lose its mapping, that may be because it was mapped last. All components seems to keep their scope setting.

**Comment by kaspersorensen** [comment]
Tried to reproduce it, and found that String analyzer lost it's mapping. So I guess it's pretty arbitrary which component(s) loose it.

**Comment by kaspersorensen** [comment]
I would be very curious to see if this is caused by UI or if it also happens if we build a job like this programmatically. Sound like a good case for a reproduction in a unittest.

**Comment by LosD** [comment]
Weird. Neither @ClaudiaPHI or I can reproduce it anymore on latest master. Some other fix/change that fixed this?

@kaspersorensen, can you reproduce anymore?

**Comment by kaspersorensen** [comment]
I could imagine that maybe the resolution of #616 fixed this transitively. I need to be at work to try and reproduce as my laptop here is crap :-P

**Comment by ClaudiaPHI** [comment]
I could reproduce it again using orderdb instead.

**Comment by LosD** [comment]
I couldn't reproduce using _orderdb_, but could using _customers_. I guess it is pretty random

**Comment by LosD** [comment]
Finally got a debugger on it. Here's a thread dump from _Create Excel spreadsheet_ when the columns are being nuked: https://gist.github.com/LosD/76df6e6b536fd3775bbd

The thread it is happening on is the first in the dump, tid 0x38

**Comment by LosD** [comment]
I'm not sure, but I think the issue could be one of, or a combination of, several problems:
- analysisJobBuilder listeners are re-added if they were already added (your's truly made sure of that. Public flogging _is_ allowed).
- Combining local and global listeners does not remove duplicate listeners in the component builders.
- It would seem that _Create Excel spreadsheet_'s listeners wasn't removed from the root analysisJobBuilder, even though _Create Excel spreadsheet_ was.

**Comment by LosD** [comment]
I think I can recreate it every time now:
After adding _Create Excel spreadsheet_ and _String analyzer_, but before changing their scope (with the "link xxxx to..."), open the dialog, but do not close them afterwards, just click back in the main window.

This seems to keep their listeners on the root scope, which makes them react when the new component is added.
