### ISSUE TITLE
Performance optimizations (wrt remote transformers)

### ISSUE THREAD

**Issue by jakubneubauer** [datacleaner/DataCleaner#713]
We run the DC monitor and bombarded it with requests to run String concatenator on 1 row. The requests were sent in 15 threads. During this tests we monitored DC monitor with JProfiler.
Within this issue we would like to discuss the observations and possible solutions in a related branch/pull request.

**Comment by jakubneubauer** [comment]
First observation:
![dc-jprofiler-1](https://cloud.githubusercontent.com/assets/1188613/10189449/6c28651a-6766-11e5-9862-2f310e2ea9a7.png)

We can see 2 things:
1. Lot of time is spent inside Jetty, resp. Spring filters (probably security etc.)
2. The REST API need to do a lot of deserialization of properties and columns from strings. The StringConverter initializes DelegatingConverter each time it is called, which is costly.

**Comment by jakubneubauer** [comment]
Second observation:
![dc-jprofiler-2](https://cloud.githubusercontent.com/assets/1188613/10189533/008175a8-6767-11e5-93cc-5e8024138786.png)

ConfiguredPropertyDescriptor getters are called very often and despite the fact that the return values are always the same, a lot of time is spent in the getters in summary. The values should be pre-computed.

**Comment by jakubneubauer** [comment]
For the record: after commits @a388b03 and @5e8da59 the time spent inside the rest controller itself (it means org.datacleaner.monitor.server.controllers.ComponentControllerV1.processStateless) dropped from 28.7% to 5.1%. So not much room to optimize there.
What can we focus now? Security filters?

**Comment by kaspersorensen** [comment]
In general I would worry less about the performance of the stateless invocation. When you use this you sorta know that now I'm doing it in the expensive way for the individual node, but that it can scale horizontally. I would worry only about the performance of the stateful invocation (where caching should in deed be active as part of the state) since that has to do with single node execution.

**Comment by kaspersorensen** [comment]
... and batches

**Comment by jakubneubauer** [comment]
Ok, so I did basic measurement for batching. I called the REST API with batches of 100 rows. Before the optimization changes, the profiling picture looks like this:
![dc-jprofiler-3](https://cloud.githubusercontent.com/assets/1188613/10195839/edf0773a-678f-11e5-90a1-99598eed4ac5.png)

I believe this confirms my focus on StringConverter.

**Comment by kaspersorensen** [comment]
Do you have a screenshot where we can see the time spent on the various filters or spring beans?

**Comment by kaspersorensen** [comment]
I think we addressed this, no.
