### ISSUE TITLE
"Execute without Analyzers" window exception

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#742]
Scenario: 

1. Start a job with orderDB as datastore 
2. Add on canvas Customers and Employees table 
3. Add a "Union " and select all column 
4. Press Execute button 
5. "Execute without analyzers" window appears. 

<b> Exception 1 </b>
6.  Select "Write to CSV" 
 The following exception occurs: 

```

Unexpected error!
 

Message:
    java.lang.IllegalArgumentException: Invalid value type: java.io.File, expected: org.apache.metamodel.util.Resource
Level:
    SEVERE
Stack Trace:
Invalid value type: java.io.File, expected: org.apache.metamodel.util.Resource
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredPropertyIfChanged(AbstractComponentBuilder.java:350)
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredProperty(AbstractComponentBuilder.java:292)
    org.datacleaner.job.builder.AnalyzerComponentBuilder.setConfiguredProperty(AnalyzerComponentBuilder.java:326)
    org.datacleaner.job.builder.AnalyzerComponentBuilder.setConfiguredProperty(AnalyzerComponentBuilder.java:58)
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredProperty(AbstractComponentBuilder.java:287)
    org.datacleaner.panels.ExecuteJobWithoutAnalyzersDialog$2.actionPerformed(ExecuteJobWithoutAnalyzersDialog.java:150)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
```
![screen shot 2015-10-07 at 2 12 32 pm](https://cloud.githubusercontent.com/assets/6339923/10337098/cde2905e-6cfd-11e5-9bfb-252d20f0996a.png)

```

**Comment by kaspersorensen** [comment]
nice catch ... I imagine this will happen regardless of the union component actually. It seems that our "execute without analyzers" action needs to be updated to use FileResource instead of File

**Comment by ClaudiaPHI** [comment]
and the "Write an Excel spreadsheet" as well. Both have "issues"

**Comment by kaspersorensen** [comment]
Ok! Luckily I think they're easy fixes. So let's get them :)

**Comment by ClaudiaPHI** [comment]
Split this issue in 2.  

This issue will handle the writing to a file. 

Issue #https://github.com/datacleaner/DataCleaner/issues/744 handles the "Union" part of it.
