### ISSUE TITLE
Address correction wizard's drill-to-details panel is empty

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/DataCleaner#743]
The value distribution step: 

The panel that was supposed to show the records that are null is empty: 

![screen shot 2015-10-07 at 2 41 31 pm](https://cloud.githubusercontent.com/assets/6339923/10337846/befe41e6-6d02-11e5-8c06-a40385794d24.png)

P.S. If you find a better title for this issue please update it :-P

**Comment by kaspersorensen** [comment]
I think this bug has it's roots in the Value Distribution Swing Renderer somehow.
