### ISSUE TITLE
Incompletely configured components in output data streams does not show in window

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#781]
The main window looks happy even if a component in an output data stream has problems.
![image](https://cloud.githubusercontent.com/assets/1282832/10429265/99c60938-70f7-11e5-8119-28e5c4e8df91.png)
(Note the Excel component with an issue, but the text in the bottom says "Ready to execute")

**Comment by ClaudiaPHI** [comment]
Before: 

![screen shot 2015-10-13 at 2 02 37 pm](https://cloud.githubusercontent.com/assets/6339923/10454203/40f0ab9e-71b3-11e5-9fd2-e123f86a02bb.png)


After: 

![screen shot 2015-10-13 at 1 57 13 pm](https://cloud.githubusercontent.com/assets/6339923/10454206/473944de-71b3-11e5-82c6-0c1b2d950559.png)
