### ISSUE TITLE
Delete from table's icon resembles too much a warning

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#784]
The red symbol in the lower-left corner of the ```Delete from table``` looks terribly lot like the validation error symbols that may occur in other components when their configuration is invalid.

See example below:

![image](https://cloud.githubusercontent.com/assets/291450/10448214/99c59860-718b-11e5-99b2-a05037dce144.png)

We should find a way to better symbolize the deletion of a record. Maybe mark the cells in red or maybe put the X/minus symbol on the line of the record or something. A bit of experimentation probably needed.

**Comment by kaspersorensen** [comment]
Suggestion 1:
![image](https://cloud.githubusercontent.com/assets/291450/10451429/74e98280-71a0-11e5-9421-207bf08555d4.png)

Suggestion 2:
![image](https://cloud.githubusercontent.com/assets/291450/10451443/8f31852a-71a0-11e5-9f89-b495f2114776.png)

**Comment by drexler42** [comment]
I like suggestion 2 better than suggestion 1. Although with suggestion 2 it could also mean delete table.
But that is hard to avoid.

**Comment by kaspersorensen** [comment]
Good point. With that in mind, maybe another iteration will help...

Suggestion 3:
![image](https://cloud.githubusercontent.com/assets/291450/10452961/e849a31a-71a8-11e5-9faf-c4ff5b77b8b0.png)

**Comment by ClaudiaPHI** [comment]
I vote for "door" nr 3. It the most suggestive.

**Comment by drexler42** [comment]
Yes - much better! It says delete Row, but then in nicely colored pixels. This is much better!

**Comment by kaspersorensen** [comment]
:dancers:
