### ISSUE TITLE
Remote jobs in DC menu

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#808]
Remote jobs (from monitor) should be available in the DC desktop so that they can be dragged on the canvas and run. Analysis result will be thrown away and only output columns will be returned.

**Comment by kaspersorensen** [comment]
Can you explain this feature some more. I don't think I even understand what you mean 😀

**Comment by jhorcicka** [comment]
My vision is to have another top-level category in the left-side tree in the desktop: "Remote jobs". Under this category there is an icon for each job that is provided by a remote monitor. These jobs can be added into the current workflow. There are some inputs and outputs. Functionality would be similar to the InvokeChildAnalysisJobTransformer. The difference is that you don't have to use that transformer and set it for each job you want to use. All jobs would be predefined for you. 

Is it better? :-)

**Comment by kaspersorensen** [comment]
Right ... I like the idea a lot actually! I think it needs a bit of thinking/discussion before we go ahead and do implementation, but this is an exciting thought.

**Comment by kaspersorensen** [comment]
No longer relevant since DataCloud is not in community edition.
