### ISSUE TITLE
Invoke child Analysis Job transformer does not work

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#829]
When playing with InvokeChildAnalysisJobTransformer and trying to run a job from local xml file, the property "Analysis job" is not remembered in the configuration dialog of the transformer. 

No output column is provided after input columns are specified. 

"Property 'Analysis job' is not properly configured" exception is thrown during "Preview data" action. 

Master's version from Friday morning (October 16) is working fine.

**Comment by kaspersorensen** [comment]
This is fixed with #830
