### ISSUE TITLE
HTML rendered Value Distribution result bar charts are missing

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#840]
I just did a "What's in my data" analysis on orderdb CUSTOMERS table. And then exported the result as HTML.

For some reason the value distribution result did not have any charts.

**Comment by ClaudiaPHI** [comment]
The export of value distribution in standalone mode  as HTML works fine. 
The issue might come from 'Country standardizer'. The Html exported result is empty for this component.

**Comment by kaspersorensen** [comment]
Or a combination. It was in deed on the Value distribution page that charts was missing. But the same result file also had other result types, incl. Country Standardizer and Pattern finder.

**Comment by ClaudiaPHI** [comment]
I looked more into it and there is a sort of race condition issue. When it has so many tabs to render, the browser doesn't load in time the javascript library that draws the chart. The theory can be tested by reloading the tab. After reloading the chart will be visible.

**Comment by ClaudiaPHI** [comment]
- Chrome has problems loading the javascript file that draws the chart. 
- Mozilla & Safari work fine.

**Comment by LosD** [comment]
Found the issue: We're not waiting for document.ready() before we try to render the charts. That means that the id looked for does not exist yet, so it cannot draw a chart.

Solution is wrapping draw calls in this construct:
```javascript
      wait_for_script_load('jQuery', function() {
        $(function(){
          draw_xxxx_xxxxx(elementId, data, 2);
        });
      });
```

In the long term, we should probably make one big block inside the jQuery ready handler where we add all rendering code. That way, it should also be possible to use requireJS for JS loading.
