### ISSUE TITLE
Moving a 'scoped' component back to default scope leaves dependent components in strange state

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#841]
If I build a job like this:
![image](https://cloud.githubusercontent.com/assets/291450/10603414/2cd2fb10-771e-11e5-8c8b-2fde09f6e502.png)
(could be any components, as long as they are 1) a output data stream producer, 2) a transformer that consumes the stream and 3) a consumer of the transformer).

If I then go to the transformers dialog and change it's scope back to default scope the graph shows like this (which is fine):
![image](https://cloud.githubusercontent.com/assets/291450/10603449/5c986736-771e-11e5-8fbb-76b8186970f3.png)

But the trouble is that if I open the third components configuration dialog it still shows the transformed input column in the input listing:
![image](https://cloud.githubusercontent.com/assets/291450/10603480/7f70ca6e-771e-11e5-9dd5-261343e646ce.png)

I would have expected this column to be removed from the child job completely, making the input here empty.

**Comment by LosD** [comment]
Fixed in master, probably by #1482 (A fix for #1470/#1339)
