### ISSUE TITLE
NLCC transformer link problem

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#845]
In desktop workflow, when trying to link a datasource to "NL Address Correction/Suppression (NLCC)" transformer via "Link to...", the arrow is not created.

**Comment by jhorcicka** [comment]
Actually this was related to all remote components. RemoteConfiguredPropertyDescriptor did not provide the property's argument type. Now Object.class is returned as default value in all cases which makes the linking possible with the first item (of type Object).

**Comment by kaspersorensen** [comment]
Hmm interesting ... This means that we don't retain property type arguments? That's a bit dangerous since many wirings depend on them for validating that the input mapping is even possible. I could imagine quite some ClassCastExceptions happening (probably on the server) if we get this wrong.

**Comment by jakubneubauer** [comment]
I didn't tested it, but I expect it too, if user wires non-matching input columns to some transformer property (input column). It is  something to be done. Let's create issue for it.

**Comment by LosD** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/1282832/18430699/e5edf466-78d9-11e6-9505-cfe69630696b.png)
![image](https://cloud.githubusercontent.com/assets/1282832/18430703/ea9c91b6-78d9-11e6-9e95-93d8cf2c7c8a.png)
