### ISSUE TITLE
Encoded password with prefix

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#865]
In conf.xml the password for a remote server is in encoded form which is not always simply recognizable from a not encoded one. That's why there should be a clear prefix that would differentiate it. 

Current state:
oFm53KJ9K+w= is encoded "admin" but could as well be the value itself. It is hard to tell for sure. 

Suggested state:
"encoded:oFm53KJ9K+w=" for the encoded variant
"admin" for a plain text variant

**Comment by kaspersorensen** [comment]
I would recommend just "enc:" as a prefix since this is used also for datastore password storage etc. Let's make sure it's as consistent as we can.

**Comment by jhorcicka** [comment]
OK
