### ISSUE TITLE
Clicking "Link [stream] to..." should show configuration dialog of target component

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#908]
When creating a link from a output data stream producer to a consumer of the stream, the auto-mapping of input should also be aided by showing the dialog of the target component.

For instance: When linking "duplicate records" from "Duplicate detection" to a "Merge duplicates" component. Nothing happens in this case.

**Comment by LosD** [comment]
This is not a general issue. I believe it is linked to having no mappable columns (As far as I remember, these are deliberately removed from the merge duplicates to avoid confusion with the synthetic columns), in which case all mapping logic (including showing the configuration dialog) is skipped.

It should be pretty simple to fix.
