### ISSUE TITLE
Component scope not changed when creating link from a scoped filter

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#909]
When "Link to" is used to wire a transformer and another component, then we automatically ensure that the target component gets the same scope as the originating transformer.

The same should be the case for filters - that if I have e.g. an Equals filter within a child-job-builder, and I use "Link to" to wire it to a target component, then the target component's scope should be changed to match the filter's.

**Comment by LosD** [comment]
I'm not sure that would be ideal; The normal way to use a filter is to add it, and then link it to an existing component.

An example:
Adding a completeness analyzer, and doing i.e. pattern analysis on some columns of the incomplete records. If we add a filter to that, the natural thing to do is to drag it in, and then link it to the pattern analyzer. But if we do that, we yank the analyzer into the global scope, which is probably not what was intended. Furthermore, if the input columns for the analyzer were carefully selected, we just lost that information.

The best solution would probably be to have filters be scope-less, but that is probably not an easy task (although I think as a concept, there isn't really anything that binds most filters to a single scope).

Until we can do something about that, I believe it would be better to move the filter into the target's scope unless it is already filtering other components. It is perhaps a little inconsistent, but I still think it would be the least surprising outcome for the user.

What do you think @kaspersorensen?

**Comment by kaspersorensen** [comment]
I think the misunderstanding here is in your sentence "The best solution would probably be to have filters be scope-less". Actually that wouldn't make sense because like other components a filter is applied to a column. And when it evaluates something, it does it on a row. Both column and row are in a particular scope.

Coming back to "constructive thinking" - if you really think we shouldn't just move the target component into the source component's scope, then we might give him 2 options: Either move the target component to the source component's scope. Or more the source component to the target component's scope. Both options will most likely leave one of the components in an inconsistent state. Which is why I tend to prefer moving the target component to the source component's scope AND then showing the target component's dialog so that any inconsistencies can be mended.

**Comment by LosD** [comment]
Ah, yeah of course. I was thinking from the point of a max-rows filter. It wouldn't make sense for other filters.

Maybe then we should generally warn when a configured component would change scope? When we don't have undo, it's pretty bad that we nuke the inputcolumn configuration without warning.

**Comment by LosD** [comment]
That makes sense.
