### ISSUE TITLE
File/URL datastores created in "Build new job" does not get show path.

### ISSUE THREAD

**Issue by LosD** [datacleaner/DataCleaner#965]
When registering a file-based datastore in the datastore manager, the full path will be saved as description.

If done through the "Build new job" wizard, only the file name is stored. Not really serious, but still an inconsistency.

**Comment by arjansh** [comment]
@LosD I can't reproduce this. For me in both cases it saves the full path as description. Can you double check this?

**Comment by LosD** [comment]
Seems to work properly now. Let's close it
