### ISSUE TITLE
Flag for components' variant (remote/local) in XML file

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#966]
In XML representation of a component (transformer) we want to have a flag differentiating the variant (remote/local). 

When we decide how to solve the remote/local variant interchangeability problem, we can use this flag. Already created jobs will be still compatible.

**Comment by kaspersorensen** [comment]
I think we decided previously to keep this as just a metadata key in the component metadata. Just like X/Y coordinates and other things. I also recall we discussed that it would have a value type that would be either "local" or the name/id of the remote server used.

**Comment by jhorcicka** [comment]
OK, I will put it into metadata-properties. 

I have doubts about the value (server name/id), though. Is it really a good approach? There are URL, name, username and password for each server in the configuration. If you mean the "name", it is just a description in one's configuration, I think. What if I want to share the job file among multiple users/desktops? Everyone can have even the same remote server named differently. In this case, I think it would be better to use the URL then (maybe this is what you had in your mind). However, this would not solve the problem with sharing the job among various remote servers that could provide the same remote component (or at least a compatible one). 

I thought the value "local"/"remote" or just a boolean flag (remote=true/false) could do the trick. What is wrong with this?

**Comment by kaspersorensen** [comment]
I can live with local/remote too, but my idea was to just use it as a hint anyway, because remotes are anyways going to be sometimes available etc. So my idea was to do it a la this:

```
final String componentOriginHint = ...
if ("local".equals(componentOriginHint) {
  // get the component from local descriptor provider
} else {
  DescriptorProvider dp = getRemoteDescriptorProviderByName(componentOriginHint);
  if (dp == null) {
    // get the component from the top-level descriptor provider
  } else {
    // get the component from the specific remote descriptor provider
  }
}
```

**Comment by kaspersorensen** [comment]
And I also expect the remotes to be somewhat systematically named. For example our "central" one would always have a fixed name like "DataCloud". And any customer who has their own server would probably give it a fixed name and tell all users to add an entry into conf.xml, which includes that specific name.

**Comment by jhorcicka** [comment]
Very well then. This seems reasonable.
