### ISSUE TITLE
Advanced merge component looses it's field mapping when changing the configuration

### ISSUE THREAD

**Issue by drexler42** [datacleaner/DataCleaner#978]
When using the Advanced Merge component, the configuration goes for a toss when I open the component in DataCleaner and change something (set threshold, add a field, anything).

Scenario:

- prepare something that can be merged and create a DC job for it.
- Add Advanced merge component. Create some field groups and merge strategies
- add csv for saving merged results.
- close configuration and save
- open advanced merge component configuration again.
- change somethind
- close configuration, then re-open.

What is wrong:
- All field definitions in the field groups are gone.
- Many output fields are gone

**Comment by kaspersorensen** [comment]
Here's what I see - the groups are still there, but the fields have dissappeared:

![image](https://cloud.githubusercontent.com/assets/291450/11689263/6a51fd84-9e91-11e5-9e68-a52f291836d2.png)

**Comment by drexler42** [comment]
Yes, that is exactly what I saw as well. But I also observed that most of the output fields disappeared. I mean the fields like "first name (merged)" and so on. Do you see that as well?

**Comment by kaspersorensen** [comment]
Yes. OK we have a fix available in the Merge project now. I will close this issue since actually it should be tracked on our JIRA then.
